(()=>{'use strict';
const KEY='mausam_alert_state_v1',HIST='mausam_alert_history_v1';
const LEVELS={critical:{label:'अत्यन्त गम्भीर',icon:'🔴'},warning:{label:'चेतावनी',icon:'🟠'},advisory:{label:'सावधानी',icon:'🟡'},info:{label:'सूचना',icon:'🔵'}};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const hash=s=>{let h=0;for(const c of String(s)){h=((h<<5)-h)+c.charCodeAt(0);h|=0}return String(h)};
function evaluate(w,loc={}){const a=[];const h=w?.hourly||{},n=Math.min(24,h.time?.length||0);for(let i=0;i<n;i++){const pp=+h.precipitation_probability?.[i]||0,g=+h.wind_gusts_10m?.[i]||0,c=+h.cape?.[i]||0,t=+h.apparent_temperature?.[i]||+h.temperature_2m?.[i]||0;if(pp>=90)a.push({level:'warning',type:'rain',title:'भारी वर्षा सम्भावना',message:`${loc.name||'तपाईंको स्थानमा'} आगामी समयमा वर्षाको सम्भावना ${pp}% सम्म छ।`,time:h.time[i],value:pp});else if(pp>=70)a.push({level:'advisory',type:'rain',title:'वर्षा सावधानी',message:`${loc.name||'तपाईंको स्थानमा'} वर्षाको सम्भावना ${pp}% छ।`,time:h.time[i],value:pp});if(g>=60)a.push({level:'warning',type:'wind',title:'बलियो हावा',message:'हावाको झोंका 60 km/h वा बढी पुग्न सक्ने संकेत छ।',time:h.time[i],value:g});if(c>=1000)a.push({level:'warning',type:'lightning',title:'चट्याङ सावधानी',message:'उच्च convective potential देखिएको छ।',time:h.time[i],value:c});if(t>=40)a.push({level:'warning',type:'heat',title:'अत्यधिक गर्मी संकेत',message:`महसुस हुने तापक्रम ${t.toFixed(1)}°C सम्म पुग्न सक्छ।`,time:h.time[i],value:t})}return a.slice(0,12)}
function publish(alert){const id=hash(alert.type+'|'+alert.time+'|'+alert.message),hist=read(HIST,[]);if(hist.some(x=>x.id===id))return false;hist.unshift({...alert,id,createdAt:Date.now()});write(HIST,hist.slice(0,100));window.dispatchEvent(new CustomEvent('mausam-alert',{detail:alert}));return true}
function notify(alert){const state=read(KEY,{});if(!state.push||typeof Notification==='undefined'||Notification.permission!=='granted')return;navigator.serviceWorker?.ready.then(r=>r.showNotification(alert.title,{body:alert.message,tag:'mausam-'+alert.type,icon:'./?icon=weather',badge:'./?icon=weather',data:{url:location.href,alert}})).catch(()=>{})}
window.MausamAlerts={LEVELS,evaluate,publish,notify,getHistory:()=>read(HIST,[]),clearHistory:()=>write(HIST,[])};
})();