(()=>{'use strict';
const WEATHER='https://api.open-meteo.com/v1/forecast',FLOOD='https://flood-api.open-meteo.com/v1/flood',AQ='https://air-quality-api.open-meteo.com/v1/air-quality',GEO='https://nominatim.openstreetmap.org/search';
const $=id=>document.getElementById(id),q=new URLSearchParams(location.search),TYPE=document.body.dataset.alert||'weather';
const DEFAULT={lat:27.7172,lon:85.324,name:'काठमाडौं'};
const TYPES={weather:{title:'🌦️ मौसम अलर्ट',sub:'वर्षा, हावा, तापक्रम र असामान्य मौसमको live संकेत'},rivers:{title:'🌊 नदी अलर्ट',sub:'नदी discharge forecast बाट जोखिम संकेत'},lightning:{title:'⚡ चट्याङ अलर्ट',sub:'मेघगर्जन र thunderstorm probability आधारित संकेत'},flood:{title:'🌊 बाढी अलर्ट',sub:'भारी वर्षा + नदी discharge को संयुक्त संकेत'},landslide:{title:'⛰️ पहिरो अलर्ट',sub:'वर्षा/भिजाइको rain-trigger संकेत'},heat:{title:'🌡️ गर्मी अलर्ट',sub:'अधिकतम तापक्रम र apparent temperature संकेत'},air:{title:'😷 वायु गुणस्तर अलर्ट',sub:'PM2.5, PM10 र AQI आधारित संकेत'},wind:{title:'💨 हावा अलर्ट',sub:'हावाको गति र gust forecast आधारित संकेत'},rain:{title:'☔ भारी वर्षा अलर्ट',sub:'precipitation probability र rainfall forecast आधारित संकेत'},uv:{title:'☀️ UV अलर्ट',sub:'UV index forecast आधारित संकेत'}};
const TYPE=TYPES[TYPE]||TYPES.weather;let place=DEFAULT;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>n==null||Number.isNaN(Number(n))?'—':Number(n).toLocaleString('ne-NP',{maximumFractionDigits:1});
const fetchJSON=async u=>{const r=await fetch(u,{cache:'no-store'});const d=await r.json();if(!r.ok||d.error)throw Error(d.reason||'API request failed');return d};
function status(label,kind){return `<span class="status ${kind}">${label}</span>`}
function classify(type,v){if(type==='heat')return v>=40?['अत्यधिक गर्मी','danger']:v>=35?['गर्मी सावधानी','warn']:['सामान्य','ok'];if(type==='wind')return v>=60?['अत्यधिक हावा','danger']:v>=40?['हावा सावधानी','warn']:['सामान्य','ok'];if(type==='rain')return v>=80?['भारी वर्षा सम्भावना','danger']:v>=50?['वर्षा सावधानी','warn']:['सामान्य','ok'];if(type==='uv')return v>=11?['अत्यधिक UV','danger']:v>=8?['उच्च UV','warn']:['सामान्य','ok'];if(type==='lightning')return v>=70?['चट्याङ उच्च सम्भावना','danger']:v>=35?['चट्याङ सावधानी','warn']:['कम संकेत','ok'];if(type==='air')return v>=150?['अस्वस्थ','danger']:v>=80?['सावधानी','warn']:['ठीक','ok'];return v>=80?['उच्च जोखिम','danger']:v>=50?['सावधानी','warn']:['कम संकेत','ok']}
function renderShell(){const t=$('title');if(t)t.textContent=TYPE==='rivers'?'नदी अलर्ट — मौसम':TYPE==='weather'?'मौसम अलर्ट — मौसम':`${TYPE} अलर्ट — मौसम`;$('heroTitle').textContent=TYPE==='rivers'?TYPES.rivers.title:TYPE==='weather'?TYPES.weather.title:TYPES[TYPE].title;$('heroSub').textContent=TYPES[TYPE].sub}
function setLocation(x){place=x||DEFAULT;$('place').textContent=place.name;$('coords').textContent=`${Number(place.lat).toFixed(3)}, ${Number(place.lon).toFixed(3)}`}
async function geolocate(){return new Promise((res,rej)=>navigator.geolocation?.getCurrentPosition(p=>res({lat:p.coords.latitude,lon:p.coords.longitude,name:'मेरो स्थान'}),rej,{enableHighAccuracy:false,timeout:8000,maximumAge:300000})||rej(Error('Location unavailable')))}
async function search(){const input=$('locationSearch'),term=input?.value.trim();if(!term)return;const box=$('searchResults');box.innerHTML='खोज्दै…';try{const r=await fetchJSON(`${GEO}?q=${encodeURIComponent(term+', Nepal')}&format=json&limit=5&accept-language=ne`);box.innerHTML=r.map(x=>`<button class="alert-row" data-lat="${x.lat}" data-lon="${x.lon}" data-name="${esc((x.display_name||x.name||term).split(',')[0])}"><span><b>${esc(x.name||term)}</b><small>${esc(x.display_name||'')}</small></span><b>→</b></button>`).join('')||'स्थान भेटिएन';box.querySelectorAll('[data-lat]').forEach(b=>b.onclick=()=>{setLocation({lat:+b.dataset.lat,lon:+b.dataset.lon,name:b.dataset.name});box.innerHTML='';run()})}catch(e){box.innerHTML=`<div class="error">खोजी असफल: ${esc(e.message)}</div>`}}
function weatherURL(extra=''){const p=new URLSearchParams({latitude:place.lat,longitude:place.lon,timezone:'auto',forecast_days:'7',hourly:'temperature_2m,apparent_temperature,precipitation_probability,precipitation,rain,weather_code,wind_speed_10m,wind_gusts_10m,uv_index,cloud_cover,cape'});if(extra)p.set('hourly',p.get('hourly')+','+extra);return `${WEATHER}?${p}`}
function baseRows(d){const h=d.hourly||{};const rows=[];for(let i=0;i<Math.min(48,h.time?.length||0);i++)rows.push({time:h.time[i],temp:h.temperature_2m?.[i],app:h.apparent_temperature?.[i],pp:h.precipitation_probability?.[i],rain:h.rain?.[i],prec:h.precipitation?.[i],wind:h.wind_speed_10m?.[i],gust:h.wind_gusts_10m?.[i],uv:h.uv_index?.[i],cape:h.cape?.[i]});return rows}
function metric(type,rows){if(type==='heat')return Math.max(...rows.map(x=>Number(x.app??x.temp??-99)));if(type==='wind')return Math.max(...rows.map(x=>Number(x.gust??x.wind??-1)));if(type==='rain'||type==='weather'||type==='landslide'||type==='flood')return Math.max(...rows.map(x=>Number(x.pp??0)));if(type==='uv')return Math.max(...rows.map(x=>Number(x.uv??0)));if(type==='lightning')return Math.max(...rows.map(x=>Number(x.light??0));return 0}
function renderWeather(d){let rows=baseRows(d);if(TYPE==='lightning'){rows=rows.map(x=>({...x,light:Number(x.cape||0)}));}
let m=metric(TYPE,rows),cl=classify(TYPE,m),label=TYPE==='heat'?'°C':TYPE==='wind'?' km/h':TYPE==='uv'?'':TYPE==='lightning'?'%':'%';$('mainMetric').textContent=fmt(m)+label;$('mainStatus').innerHTML=status(cl[0],cl[1]);$('updated').textContent=`Live forecast · ${new Date().toLocaleString('ne-NP')}`;
if(TYPE==='weather'){const severe=rows.filter(x=>x.pp>=70||x.wind>=45||x.gust>=60);m=severe.length;cl=m?['मौसम सावधानी','warn']:['सामान्य','ok'];$('mainMetric').textContent=fmt(m)+' संकेत';$('mainStatus').innerHTML=status(cl[0],cl[1])}
if(TYPE==='lightning'){const severe=rows.filter(x=>x.cape>=500);$('mainMetric').textContent=severe.length+' घण्टा';$('mainStatus').innerHTML=status(severe.length?'मेघगर्जन सम्भावना':'कम thunderstorm signal',severe.length?'warn':'ok')}
const top=rows.slice(0,24).map(x=>`<div class="alert-row"><span><b>${esc(String(x.time||'').replace('T',' '))}</b><small>वर्षा ${fmt(x.pp)}% · ${fmt(x.prec)} mm · हावा ${fmt(x.wind)} km/h</small></span>${status(TYPE==='heat'?fmt(x.app??x.temp)+'°C':TYPE==='wind'?fmt(x.gust??x.wind)+' km/h':TYPE==='uv'?fmt(x.uv):TYPE==='lightning'?(x.cape>=500?'सावधानी':'कम संकेत'):x.pp>=70?'वर्षा सम्भावित':'कम संकेत',TYPE==='heat'?(x.app>=35?'warn':'ok'):TYPE==='wind'?(x.gust>=40?'warn':'ok'):TYPE==='uv'?(x.uv>=8?'warn':'ok'):TYPE==='lightning'?(x.cape>=500?'warn':'ok'):(x.pp>=70?'warn':'ok'))}</div>`).join('');$('rows').innerHTML=top}
async function runWeather(){const d=await fetchJSON(weatherURL());renderWeather(d);}
async function runRiver(){const d=await fetchJSON(`${FLOOD}?latitude=${place.lat}&longitude=${place.lon}&daily=river_discharge,river_discharge_mean,river_discharge_p25,river_discharge_p75&forecast_days=30`);const x=d.daily||{},vals=x.river_discharge||[],mean=x.river_discharge_mean||[],p75=x.river_discharge_p75||[];const max=Math.max(...vals.map(Number));const idx=vals.findIndex(v=>Number(v)===max);const ratio=mean[idx]>0?max/mean[idx]:1;const cl=ratio>=2?['असामान्य discharge','danger']:ratio>=1.4?['नदी सावधानी','warn']:['सामान्य संकेत','ok'];$('mainMetric').textContent=fmt(max)+' m³/s';$('mainStatus').innerHTML=status(cl[0],cl[1]);$('updated').textContent='GloFAS river-discharge forecast · '+new Date().toLocaleString('ne-NP');$('rows').innerHTML=x.time?.slice(0,14).map((t,i)=>`<div class="alert-row"><span><b>${t}</b><small>discharge ${fmt(vals[i])} m³/s · median/mean ${fmt(mean[i])}</small></span>${status(i===idx?cl[0]:'पूर्वानुमान',i===idx?cl[1]:'unknown')}</div>`).join('')||'<div class="muted">नदी data उपलब्ध भएन।</div>';}
async function runAir(){const d=await fetchJSON(`${AQ}?latitude=${place.lat}&longitude=${place.lon}&timezone=auto&forecast_days=2&hourly=pm2_5,pm10,european_aqi`),h=d.hourly||{},vals=h.european_aqi||[],i=vals.findIndex(v=>Number(v)>=0);const a=Number(vals[i<0?0:i]??0),cl=classify('air',a);$('mainMetric').textContent=fmt(a)+' AQI';$('mainStatus').innerHTML=status(cl[0],cl[1]);$('updated').textContent='CAMS air-quality forecast · '+new Date().toLocaleString('ne-NP');$('rows').innerHTML=(h.time||[]).slice(0,24).map((t,j)=>`<div class="alert-row"><span><b>${t}</b><small>PM2.5 ${fmt(h.pm2_5?.[j])} · PM10 ${fmt(h.pm10?.[j])}</small></span>${status(fmt(h.european_aqi?.[j]??'—')+' AQI',Number(h.european_aqi?.[j]||0)>=80?'warn':'ok')}</div>`).join('')}
async function run(){setLocation(place);$('loading').hidden=false;$('error').hidden=true;try{if(TYPE==='rivers'||TYPE==='flood')await runRiver();else if(TYPE==='air')await runAir();else await runWeather();$('loading').hidden=true}catch(e){$('loading').hidden=true;$('error').hidden=false;$('error').textContent='डाटा ल्याउन सकिएन: '+e.message}}
$('searchBtn').onclick=search;$('locationSearch').onkeydown=e=>{if(e.key==='Enter')search()};$('locBtn').onclick=async()=>{try{setLocation(await geolocate());run()}catch{$('error').hidden=false;$('error').textContent='Location अनुमति/उपलब्धता जाँच गर्नुहोस्।'}};$('refreshBtn').onclick=run;renderShell();if(q.get('lat')&&q.get('lon'))setLocation({lat:+q.get('lat'),lon:+q.get('lon'),name:q.get('name')||'चयन गरिएको स्थान'});run();setInterval(run,900000);
})();
