(()=>{'use strict';
const API='https://api.open-meteo.com/v1/forecast',AQ='https://air-quality-api.open-meteo.com/v1/air-quality',GEO='https://nominatim.openstreetmap.org/search';
const $=id=>document.getElementById(id),fmt=v=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString('ne-NP',{maximumFractionDigits:1});
const codes={0:['सफा आकाश','☀️'],1:['मुख्यतया सफा','🌤️'],2:['आंशिक बादल','⛅'],3:['बादल लागेको','☁️'],45:['कुहिरो','🌫️'],48:['बाक्लो कुहिरो','🌫️'],51:['हल्का झरी','🌦️'],53:['मध्यम झरी','🌦️'],55:['घना झरी','🌧️'],61:['हल्का वर्षा','🌦️'],63:['मध्यम वर्षा','🌧️'],65:['भारी वर्षा','🌧️'],71:['हल्का हिमपात','🌨️'],73:['मध्यम हिमपात','🌨️'],75:['भारी हिमपात','❄️'],80:['हल्का छिटपुट वर्षा','🌦️'],81:['मध्यम छिटपुट वर्षा','🌧️'],82:['तीव्र वर्षा','⛈️'],95:['मेघगर्जन','⛈️'],96:['असिनासहित मेघगर्जन','⛈️'],99:['ठूलो असिनासहित मेघगर्जन','⛈️']};
const day=['आइतबार','सोमबार','मंगलबार','बुधबार','बिहीबार','शुक्रबार','शनिबार'];
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};const weather=c=>codes[c]||['परिवर्तनशील','🌤️'];const show=(id,on)=>{const e=$(id);if(e)e.classList.toggle('hidden',!on)};
const safe=async url=>{const r=await fetch(url,{cache:'no-store'});let body=null;try{body=await r.json()}catch{}if(!r.ok)throw Error(body?.reason||('HTTP '+r.status));if(body?.error)throw Error(body.reason||'API error');return body};
function localTime(s,tz){try{return new Intl.DateTimeFormat('ne-NP',{timeZone:tz||'UTC',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(s))}catch{return String(s||'').slice(11,16)}}
function hourIndex(times){if(!Array.isArray(times)||!times.length)return 0;const now=Date.now();let i=times.findIndex(t=>new Date(t).getTime()>=now);return i<0?times.length-1:Math.max(0,i)}
function windDir(v){if(v==null)return'—';return ['उत्तर','उत्तरपूर्व','पूर्व','दक्षिणपूर्व','दक्षिण','दक्षिणपश्चिम','पश्चिम','उत्तरपश्चिम'][Math.round(v/45)%8]}
function advice(t,r,u){if((r||0)>=60)return'☔ छाता/रेनकोट तयार राख्नुहोस्';if((u||0)>=7)return'🧴 घामबाट जोगिनुहोस्';if((t||0)>=32)return'💧 पानी धेरै पिउनुहोस्';if((t||0)<=10)return'🧥 न्यानो कपडा लगाउनुहोस्';return'🌤️ सामान्य बाहिरी गतिविधिका लागि ठीक'}
function putCurrent(d,name){const c=d.current||{},h=d.hourly||{},di=d.daily||{},tz=d.timezone||'UTC',w=weather(c.weather_code);set('place',name);set('updated',`अहिले · ${localTime(c.time||new Date().toISOString(),tz)} · ${tz}`);set('weatherIcon',w[1]);set('temp',fmt(c.temperature_2m)+'°');set('condition',w[0]);set('feels',fmt(c.apparent_temperature)+'°');set('high',fmt(di.temperature_2m_max?.[0])+'°');set('low',fmt(di.temperature_2m_min?.[0])+'°');set('rain',fmt(di.precipitation_probability_max?.[0])+'%');set('humidity',fmt(c.relative_humidity_2m)+'%');set('dTemp',fmt(c.temperature_2m)+'°C');set('dHum',fmt(c.relative_humidity_2m)+'%');set('wind',fmt(c.wind_speed_10m)+' km/h');set('windDir',windDir(c.wind_direction_10m));set('pressure',fmt(c.pressure_msl)+' hPa');set('cloud',fmt(c.cloud_cover)+'%');set('visibility',fmt(h.visibility?.[0]/1000)+' km');set('dew',fmt(h.dew_point_2m?.[0])+'°C');set('sun','☀️ '+localTime(di.sunrise?.[0],tz)+' · 🌙 '+localTime(di.sunset?.[0],tz));set('advice',advice(c.temperature_2m,di.precipitation_probability_max?.[0],di.uv_index_max?.[0]));const score=Math.max(0,Math.min(100,Math.round(100-Math.max(0,Math.abs(c.temperature_2m-24)-4)*3-(di.precipitation_probability_max?.[0]||0)*.28-Math.max(0,(c.wind_speed_10m||0)-6)*3-Math.max(0,(c.cloud_cover||0)-75)*.08-Math.max(0,(di.uv_index_max?.[0]||0)-7)*2)));set('score',score+'/100');set('scoreText',score>=80?'आजको मौसम निकै सहज छ।':score>=60?'धेरैजसो कामका लागि राम्रो दिन।':score>=40?'बाहिर निस्कँदा तयारी गर्नुहोस्।':'मौसम प्रतिकूल हुन सक्छ, सावधानी अपनाउनुहोस्।');renderHourly(h,tz);renderRain(h,tz);renderDaily(di,tz);renderAQPlaceholder();const app=$('app');if(app)app.classList.remove('hidden');show('empty',false)}
function renderHourly(h,tz){const e=$('hourly');if(!e||!Array.isArray(h.time))return;const i=hourIndex(h.time);e.innerHTML=h.time.slice(i,i+24).map((t,k)=>{const j=i+k,w=weather(h.weather_code?.[j]);return `<div class="hour ${k===0?'now':''}"><small>${k===0?'अहिले':localTime(t,tz)}</small><span>${w[1]}</span><b>${fmt(h.temperature_2m?.[j])}°</b><small>☔ ${fmt(h.precipitation_probability?.[j])}%</small></div>`}).join('')}
function renderRain(h,tz){const e=$('rainChart');if(!e||!Array.isArray(h.time))return;const i=hourIndex(h.time),p=(h.precipitation_probability||[]).slice(i,i+18),max=Math.max(1,...p.map(Number));e.innerHTML=p.map(v=>`<div class="rain-bar" style="height:${Math.max(5,Number(v||0)/max*100)}%"><small>${fmt(v)}%</small></div>`).join('');const first=p.findIndex(v=>Number(v)>=50);set('rainWindow',first<0?'ठूलो वर्षा संकेत छैन':`करिब ${localTime(h.time[i+first],tz)} मा वर्षा सम्भावित`)}
function renderDaily(d,tz){const e=$('daily');if(!e||!Array.isArray(d.time))return;e.innerHTML=d.time.map((t,i)=>{const w=weather(d.weather_code?.[i]);return `<div class="day"><b>${i===0?'आज':i===1?'भोलि':day[new Date(t+'T12:00:00').getDay()]}</b><span class="wx">${w[1]}</span><span>${w[0]}</span><span><b>${fmt(d.temperature_2m_max?.[i])}°</b> / ${fmt(d.temperature_2m_min?.[i])}° · ☔ ${fmt(d.precipitation_probability_max?.[i])}%</span></div>`}).join('')}
function renderAQPlaceholder(){set('aqi','—');set('pm25','—');set('pm10','—')}
async function loadAQ(lat,lon,tz){try{const a=await safe(`${AQ}?latitude=${lat}&longitude=${lon}&timezone=${encodeURIComponent(tz||'auto')}&hourly=pm2_5,pm10,european_aqi&forecast_days=2`);const h=a.hourly||{},i=hourIndex(h.time);set('aqi',fmt(h.european_aqi?.[i]));set('pm25',fmt(h.pm2_5?.[i]));set('pm10',fmt(h.pm10?.[i]))}catch{set('aqi','उपलब्ध छैन');set('pm25','उपलब्ध छैन');set('pm10','उपलब्ध छैन')}}
function cityCache(){try{return JSON.parse(localStorage.getItem('mausam_cities')||'[]').filter(x=>x&&Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lon)))}catch{return[]}}
function saveCity(lat,lon,name){let a=cityCache().filter(x=>Math.abs(Number(x.lat)-Number(lat))>.00001||Math.abs(Number(x.lon)-Number(lon))>.00001);a.unshift({lat:Number(lat),lon:Number(lon),name:name||'स्थान',usedAt:Date.now()});try{localStorage.setItem('mausam_cities',JSON.stringify(a.slice(0,8)));localStorage.setItem('mausam_last',JSON.stringify(a[0]))}catch{}renderSavedCities()}
function renderSavedCities(){const box=$('navResults');if(!box)return;const a=cityCache();if(!a.length){box.innerHTML='<div class="nav-results-title">⌕ शहर वा जिल्ला खोज्नुहोस्</div>';return}box.innerHTML='<div class="nav-results-title">💾 सुरक्षित शहरहरू</div>'+a.map((x,i)=>`<button class="nav-city" data-i="${i}"><span>📍</span><span><b>${x.name}</b><small>${i===0?'अन्तिम प्रयोग गरिएको':'सुरक्षित स्थान'}</small></span><em>→</em></button>`).join('');box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const x=a[Number(b.dataset.i)];closeNavResults();load(x.lat,x.lon,x.name)})}
function closeNavResults(){const b=$('navResults');if(b)b.classList.remove('open')}
function showNationalSections(on){document.querySelectorAll('#districtExplorer,#nationalPulse,#intelligence').forEach(e=>e.classList.toggle('national-hidden',!on))}
function updateNationalVisibility(){showNationalSections(cityCache().length===0&&!localStorage.getItem('mausam_last'))}
function scrollToWeather(){const app=$('app');const top=app?.getBoundingClientRect().top??0;window.scrollTo({top:Math.max(0,window.scrollY+top-12),behavior:'smooth'})}
async function load(lat,lon,name){show('empty',false);show('loading',true);const cleanLat=Number(lat),cleanLon=Number(lon);const box=$('results');if(box)box.style.display='none';closeNavResults();if(!Number.isFinite(cleanLat)||!Number.isFinite(cleanLon)){show('loading',false);return showError('स्थानको coordinates अमान्य छन्।')}try{const q=new URLSearchParams({latitude:cleanLat.toFixed(6),longitude:cleanLon.toFixed(6),timezone:'auto',forecast_days:'7',current:'temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,rain,weather_code,cloud_cover,pressure_msl,surface_pressure,wind_speed_10m,wind_direction_10m',hourly:'temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation_probability,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_direction_10m,visibility,uv_index,pressure_msl,surface_pressure',daily:'weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,precipitation_sum,rain_sum,precipitation_probability_max,wind_speed_10m_max,uv_index_max,sunrise,sunset'});const d=await safe(`${API}?${q}`);const finalName=name||'चयन गरिएको स्थान';putCurrent(d,finalName);try{localStorage.setItem('mausam_weather_snapshot_v1',JSON.stringify({at:Date.now(),data:d,lat:cleanLat,lon:cleanLon,name:finalName}))}catch{};window.dispatchEvent(new CustomEvent('mausam-weather-loaded',{detail:{lat:cleanLat,lon:cleanLon,name:finalName,data:d}}));show('loading',false);saveCity(cleanLat,cleanLon,finalName);showNationalSections(false);requestAnimationFrame(()=>scrollToWeather());loadAQ(cleanLat,cleanLon,d.timezone)}catch(e){show('loading',false);showError(e.message||'API request failed');console.error('Mausam weather error:',e)}}
function showError(reason){const app=$('app');if(app)app.classList.add('hidden');const empty=$('empty');if(empty){empty.classList.remove('hidden');const msg=empty.querySelector('[data-error],.error-message,p,small');if(msg)msg.textContent='मौसमको डाटा ल्याउन सकिएन। '+reason}else alert('मौसमको डाटा ल्याउन सकिएन। '+reason)}
function resultHTML(r,q){return r.map(x=>`<button class="result" data-lat="${x.lat}" data-lon="${x.lon}" data-name="${(x.name||x.display_name||q).split(',')[0]}"><b>${x.name||q}</b><small>${x.display_name||''}</small></button>`).join('')}
async function search(q,target='results'){q=String(q||'').trim();if(!q)return;const mainInput=$('search'),nav=$('navSearch');if(mainInput)mainInput.value=q;if(nav)nav.value=q;const box=$(target);if(box){box.innerHTML='<div class="result">खोज्दै…</div>';box.style.display='block';box.classList.add('open')}try{let r=await safe(`${GEO}?q=${encodeURIComponent(q+', Nepal')}&format=json&limit=7&accept-language=ne`);if(!Array.isArray(r)||!r.length)r=await safe(`${GEO}?q=${encodeURIComponent(q)}&format=json&limit=7&accept-language=ne`);if(box)box.innerHTML=r.length?resultHTML(r,q):'<div class="result">स्थान भेटिएन।</div>';if(box)box.querySelectorAll('[data-lat]').forEach(x=>x.onclick=()=>load(x.dataset.lat,x.dataset.lon,x.dataset.name))}catch(e){if(box)box.innerHTML='<div class="result">स्थान खोज्न सकिएन। फेरि प्रयास गर्नुहोस्।</div>';console.error('Mausam geocode error:',e)}}
function searchFromInput(input,target){if(input&&input.value.trim())search(input.value,target)}
function bindNav(){const input=$('navSearch'),clear=$('navSearchClear'),box=$('navResults');if(input){input.addEventListener('focus',()=>{renderSavedCities();box?.classList.add('open')});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchFromInput(input,'navResults')}});input.addEventListener('input',()=>{if(!input.value.trim())renderSavedCities()})}clear?.addEventListener('click',()=>{if(input){input.value='';input.focus()}renderSavedCities()});document.addEventListener('click',e=>{if(!e.target.closest('.nav-search')&&!e.target.closest('#navResults'))closeNavResults()})}
function bindMain(){const input=$('search');if(input){input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchFromInput(input,'results')}})}document.querySelectorAll('#quick [data-q]').forEach(b=>b.addEventListener('click',()=>search(b.dataset.q)));$('clear')?.addEventListener('click',()=>{if(input){input.value='';input.focus()}const r=$('results');if(r)r.style.display='none'});document.querySelectorAll('[data-lat][data-lon]').forEach(e=>{if(!e.dataset.bound){e.addEventListener('click',()=>load(e.dataset.lat,e.dataset.lon,e.dataset.name||e.textContent.trim()));e.dataset.bound='1'}})}
function bindAll(){const btn=$('allBtn'),menu=$('allMenu');btn?.addEventListener('click',()=>{if(menu)menu.hidden=!menu.hidden});$('showNationalBtn')?.addEventListener('click',()=>{showNationalSections(true);if(menu)menu.hidden=true;document.querySelector('#districtExplorer')?.scrollIntoView({behavior:'smooth',block:'start'})});document.addEventListener('click',e=>{if(!e.target.closest('.all-menu')&&!e.target.closest('#allBtn')&&menu)menu.hidden=true})}
function useMyLocation(){if(!navigator.geolocation)return showError('यो ब्राउजरले location support गर्दैन।');show('loading',true);navigator.geolocation.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude,'मेरो स्थान'),e=>{show('loading',false);showError(e.code===1?'Location अनुमति दिनुहोस्।':'Location भेटिएन।')},{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
function bind(){bindNav();bindMain();bindAll();renderSavedCities();updateNationalVisibility();$('locBtn')?.addEventListener('click',useMyLocation);$('emptyLoc')?.addEventListener('click',useMyLocation);const params=new URLSearchParams(location.search),ql=Number(params.get('lat')),qo=Number(params.get('lon')),qn=params.get('name');if(Number.isFinite(ql)&&Number.isFinite(qo)){load(ql,qo,qn||'साझा गरिएको स्थान')}else{const last=localStorage.getItem('mausam_last');if(last){try{const x=JSON.parse(last);if(x?.lat!=null&&x?.lon!=null)load(x.lat,x.lon,x.name)}catch{}}else showNationalSections(true)}const observer=new MutationObserver(()=>{if(localStorage.getItem('mausam_last'))showNationalSections(false)});observer.observe(document.querySelector('main')||document.body,{childList:true,subtree:true})}
window.load=load;window.search=search;window.loadWeather=load;window.searchWeather=search;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();