(()=>{'use strict';
const W='https://api.open-meteo.com/v1/forecast',AQ='https://air-quality-api.open-meteo.com/v1/air-quality',G='https://nominatim.openstreetmap.org/search';
const $=id=>document.getElementById(id), N=v=>v==null?'—':Math.round(v), fmt=v=>new Intl.NumberFormat('ne-NP').format(v), dayNames=['आइतबार','सोमबार','मंगलबार','बुधबार','बिहीबार','शुक्रबार','शनिबार'], monthNames=['बैशाख','जेठ','असार','साउन','भदौ','असोज','कात्तिक','मंसिर','पुस','माघ','फागुन','चैत'];
let current=null, compares=[];
const codes={0:['सफा आकाश','☀️'],1:['मुख्यतया सफा','🌤️'],2:['आंशिक बादल','⛅'],3:['बादल लागेको','☁️'],45:['कुहिरो','🌫️'],48:['बाक्लो कुहिरो','🌫️'],51:['हल्का झरी','🌦️'],53:['मध्यम झरी','🌦️'],55:['घना झरी','🌧️'],61:['हल्का वर्षा','🌦️'],63:['मध्यम वर्षा','🌧️'],65:['भारी वर्षा','🌧️'],71:['हल्का हिमपात','🌨️'],73:['मध्यम हिमपात','🌨️'],75:['भारी हिमपात','❄️'],80:['हल्का छिटपुट वर्षा','🌦️'],81:['मध्यम छिटपुट वर्षा','🌧️'],82:['तीव्र वर्षा','⛈️'],95:['मेघगर्जन','⛈️'],96:['असिनासहित मेघगर्जन','⛈️'],99:['ठूलो असिनासहित मेघगर्जन','⛈️']};
function weather(c){return codes[c]||['परिवर्तनशील','🌤️']};
function nepaliDate(d=new Date()){let y=d.getFullYear(),m=d.getMonth()+1,day=d.getDate();return `${dayNames[d.getDay()]} · ${fmt(day)} ${monthNames[(m+8)%12]} ${fmt(y+57)}`}
function set(id,v){if($(id))$(id).textContent=v};
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function time(s){return new Date(s).toLocaleTimeString('ne-NP',{hour:'numeric',minute:'2-digit',hour12:true})}
function windDir(deg){if(deg==null)return'—';return ['उत्तर','उत्तरपूर्व','पूर्व','दक्षिणपूर्व','दक्षिण','दक्षिणपश्चिम','पश्चिम','उत्तरपश्चिम'][Math.round(deg/45)%8]}
function score(temp,rain,wind,cloud,uv){let s=100;s-=Math.max(0,Math.abs(temp-24)-4)*3;s-=rain*.28;s-=Math.max(0,wind-6)*3;s-=Math.max(0,cloud-75)*.08;s-=Math.max(0,uv-7)*2;return Math.max(0,Math.min(100,Math.round(s)))}
function scoreText(s){return s>=80?'आजको मौसम निकै सहज छ।':s>=60?'धेरैजसो कामका लागि राम्रो दिन।':s>=40?'बाहिर निस्कँदा तयारी गर्नुहोस्।':'मौसम प्रतिकूल हुन सक्छ, सावधानी अपनाउनुहोस्।'}
function advice(temp,rain,uv){if(rain>=60)return'☔ छाता/रेनकोट तयार राख्नुहोस्';if(uv>=7)return'🧴 घामबाट जोगिनुहोस्';if(temp>=32)return'💧 पानी धेरै पिउनुहोस्';if(temp<=10)return'🧥 न्यानो कपडा लगाउनुहोस्';return'🌤️ सामान्य बाहिरी गतिविधिका लागि ठीक'}
function story(d,h){let rain=Math.max(...d.precip_probability_max), hi=Math.max(...d.temperature_2m_max),lo=Math.min(...d.temperature_2m_min);return `आज ${h.condition} रहने सम्भावना छ। तापक्रम करिब ${fmt(N(hi))}° देखि ${fmt(N(lo))}° सम्म रहनेछ। वर्षाको अधिकतम सम्भावना ${fmt(N(rain))}% छ। बिहानदेखि साँझसम्मको अवस्था हेरेर आफ्नो काम मिलाउनुहोस्।`}
async function search(q){if(!q.trim())return;let box=$('results');box.innerHTML='<div class="result">खोज्दै…</div>';box.style.display='block';try{let a=await json(`${G}?q=${encodeURIComponent(q)},Nepal&format=json&limit=7&accept-language=ne`);box.innerHTML=a.length?a.map(x=>`<div class="result" data-lat="${x.lat}" data-lon="${x.lon}" data-name="${(x.display_name||q).split(',')[0]}"><b>${x.name||q}</b><small>${x.display_name||'नेपाल'}</small></div>`).join(''):'<div class="result">स्थान भेटिएन।</div>';box.querySelectorAll('.result[data-lat]').forEach(e=>e.onclick=()=>{box.style.display='none';load(+e.dataset.lat,+e.dataset.lon,e.dataset.name)})}catch(e){box.innerHTML='<div class="result">खोजी असफल भयो। इन्टरनेट जाँच्नुहोस्।</div>'}}
async function load(lat,lon,name,add=true){$('empty').classList.add('hidden');$('app').classList.add('hidden');$('loading').classList.remove('hidden');try{let params=new URLSearchParams({latitude:lat,longitude:lon,timezone:'Asia/Kathmandu',forecast_days:7,current:'temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,rain,weather_code,cloud_cover,pressure_msl,surface_pressure,wind_speed_10m,wind_direction_10m,visibility,dew_point_2m',hourly:'temperature_2m,apparent_temperature,precipitation_probability,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,uv_index',daily:'weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,precipitation_sum,rain_sum,precipitation_probability_max,wind_speed_10m_max,uv_index_max,sunrise,sunset'});let [d,a]=await Promise.all([json(W+'?'+params),json(`${AQ}?latitude=${lat}&longitude=${lon}&timezone=Asia%2FKathmandu&hourly=pm2_5,pm10,european_aqi`)]);current={lat,lon,name,d,a};render();if(add&&!compares.some(x=>Math.abs(x.lat-lat)<.001&&Math.abs(x.lon-lon)<.001)){compares.unshift({lat,lon,name,temp:d.current.temperature_2m,code:d.current.weather_code});compares=compares.slice(0,3)}renderCompare();localStorage.setItem('mausam_last',JSON.stringify({lat,lon,name}))}catch(e){alert('मौसमको डाटा ल्याउन सकिएन। केही समयपछि फेरि प्रयास गर्नुहोस्।')}finally{$('loading').classList.add('hidden')}}
function render(){let {d,a}=current,c=d.current,di=d.daily,h=d.hourly,w=weather(c.weather_code);set('place',current.name);set('updated',nepaliDate()+' · अन्तिम अपडेट '+time(new Date()));set('weatherIcon',w[1]);set('temp',N(c.temperature_2m)+'°');set('condition',w[0]);set('feels',N(c.apparent_temperature)+'°');set('high',N(di.temperature_2m_max[0])+'°');set('low',N(di.temperature_2m_min[0])+'°');set('rain',N(di.precipitation_probability_max[0])+'%');set('humidity',N(c.relative_humidity_2m)+'%');set('advice',advice(c.temperature_2m,di.precipitation_probability_max[0],di.uv_index_max[0]));set('sun','☀️ '+time(di.sunrise[0])+' · 🌙 '+time(di.sunset[0]));let s=score(c.temperature_2m,di.precipitation_probability_max[0],c.wind_speed_10m,c.cloud_cover,di.uv_index_max[0]);set('score',s+'/100');set('scoreText',scoreText(s));set('umbrella',di.precipitation_probability_max[0]>=50?'हो':'अहिले आवश्यक छैन');set('umbrellaText',di.precipitation_probability_max[0]>=50?'वर्षाको सम्भावना उल्लेख्य छ।':'वर्षा सम्भावना कम छ।');set('travel',di.precipitation_probability_max[0]>=70||c.weather_code>=95?'सावधानी':'सामान्य');set('travelText',di.precipitation_probability_max[0]>=70?'वर्षा/चिप्लो बाटोको सम्भावना हेर्नुहोस्।':'सामान्य यात्राका लागि मौसम अनुकूल।');set('clothes',c.temperature_2m>=30?'हल्का कपडा':c.temperature_2m<=15?'न्यानो कपडा':'आरामदायी कपडा');set('clothesText','तापक्रम र UV अनुसार कपडा मिलाउनुहोस्।');set('story',story(di,{condition:w[0]}));set('farmTip',di.precipitation_probability_max[0]>60?'सिँचाइ अघि वर्षाको सम्भावना जाँच्नुहोस्।':'खेतीका बाहिरी कामका लागि समय अनुकूल देखिन्छ।');set('healthTip',di.uv_index_max[0]>=7?'दिउँसो घामबाट जोगिनुहोस् र पानी पिउनुहोस्।':'सामान्य बाहिरी गतिविधिमा हाइड्रेटेड रहनुहोस्।');set('dTemp',N(c.temperature_2m)+'°C');set('dHum',N(c.relative_humidity_2m)+'%');set('wind',N(c.wind_speed_10m)+' km/h');set('windDir',windDir(c.wind_direction_10m));set('pressure',N(c.pressure_msl)+' hPa');set('visibility',N(c.visibility/1000)+' km');set('cloud',N(c.cloud_cover)+'%');set('dew',N(c.dew_point_2m)+'°C');renderHourly(h,c);renderRain(h);renderDaily(di);renderAQ(a,di)}
function renderHourly(h,c){let idx=h.time.findIndex(x=>new Date(x)>=new Date());idx=Math.max(0,idx);$('hourly').innerHTML=h.time.slice(idx,idx+24).map((t,i)=>{let j=idx+i,w=weather(h.weather_code[j]);return `<div class="hour ${i===0?'now':''}"><small>${i===0?'अहिले':time(t)}</small><span>${w[1]}</span><b>${N(h.temperature_2m[j])}°</b><small>☔ ${N(h.precipitation_probability[j])}%</small></div>`}).join('')}
function renderRain(h){let idx=h.time.findIndex(x=>new Date(x)>=new Date());idx=Math.max(0,idx);let p=h.precipitation_probability.slice(idx,idx+18),max=Math.max(1,...p);$('rainChart').innerHTML=p.map((v,i)=>`<div class="rain-bar" style="height:${Math.max(5,v/max*100)}%"><small>${N(v)}%</small></div>`).join('');let first=p.findIndex(v=>v>=50), last=p.map((v,i)=>v>=50?i:-1).filter(i=>i>=0).pop();set('rainWindow',first<0?'ठूलो वर्षा संकेत छैन':`करिब ${time(h.time[idx+first])}${last>first?' देखि '+time(h.time[idx+last]):' मा वर्षा सम्भावित'}`);set('rainNote',first<0?'अर्का १८ घण्टामा ५०% भन्दा माथिको वर्षा सम्भावना देखिएको छैन।':'वर्षा सम्भावना बढेको समयलाई हाइलाइट गरिएको छ।')}
function renderDaily(d){$('daily').innerHTML=d.time.map((t,i)=>{let w=weather(d.weather_code[i]);return `<div class="day"><b>${i===0?'आज':i===1?'भोलि':dayNames[new Date(t+'T12:00:00').getDay()]}</b><span class="wx">${w[1]}</span><span>${w[0]}</span><span><b>${N(d.temperature_2m_max[i])}°</b> / ${N(d.temperature_2m_min[i])}° · ☔ ${N(d.precipitation_probability_max[i])}%</span></div>`}).join('')}
function renderAQ(a,d){let h=a.hourly,idx=h.time.findIndex(x=>new Date(x)>=new Date());idx=Math.max(0,idx);let pm=h.pm2_5[idx],pm10=h.pm10[idx],aq=h.european_aqi[idx],uv=d.uv_index_max[0];set('pm25',N(pm));set('pm10',N(pm10));set('aqi',N(aq));set('aqiText',aq<=20?'राम्रो':aq<=40?'ठीकठाक':aq<=60?'मध्यम':'खराब');set('aqiBadge',aq<=20?'राम्रो वायु':aq<=40?'सामान्य':'सावधानी');set('uv',N(uv));set('uvText',uv<3?'कम':uv<6?'मध्यम':uv<8?'उच्च':'धेरै उच्च')}
function renderCompare(){if(!compares.length)return;let el=$('compareList');el.innerHTML=compares.map(x=>`<div class="compare-item"><b>${x.name}</b><div>${weather(x.code)[1]} ${N(x.temp)}°C</div></div>`).join('')}
function locate(){if(!navigator.geolocation)return alert('तपाईंको ब्राउजरले स्थान सुविधा समर्थन गर्दैन।');navigator.geolocation.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude,'मेरो हालको स्थान'),()=>alert('स्थान अनुमति प्राप्त भएन।'))}
$('search').addEventListener('input',e=>{clearTimeout(window.st);window.st=setTimeout(()=>search(e.target.value),450)});$('clear').onclick=()=>{$('search').value='';$('results').style.display='none'};document.querySelectorAll('#quick button').forEach(b=>b.onclick=()=>{$('search').value=b.dataset.q;search(b.dataset.q)});$('locBtn').onclick=locate;$('emptyLoc').onclick=locate;$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('mausam_dark',document.body.classList.contains('dark'))};$('shareBtn').onclick=()=>{if(!current)return;if(navigator.share)navigator.share({title:'मौसम',text:`${current.name} को अहिलेको मौसम: ${$('temp').textContent}, ${$('condition').textContent}`,url:location.href});else navigator.clipboard?.writeText(location.href).then(()=>alert('लिङ्क कपी भयो।'))};$('addCompare').onclick=()=>{$('search').focus();alert('तुलना गर्न अर्को शहर खोज्नुहोस्।')};
if(localStorage.getItem('mausam_dark')==='true')document.body.classList.add('dark');try{let x=JSON.parse(localStorage.getItem('mausam_last'));if(x)load(x.lat,x.lon,x.name)}catch{};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();