(()=>{'use strict';
const API='https://api.open-meteo.com/v1/forecast',AQ='https://air-quality-api.open-meteo.com/v1/air-quality',GEO='https://nominatim.openstreetmap.org/search';
const $=id=>document.getElementById(id), fmt=v=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString('ne-NP',{maximumFractionDigits:1});
const codes={0:['सफा आकाश','☀️'],1:['मुख्यतया सफा','🌤️'],2:['आंशिक बादल','⛅'],3:['बादल लागेको','☁️'],45:['कुहिरो','🌫️'],48:['बाक्लो कुहिरो','🌫️'],51:['हल्का झरी','🌦️'],53:['मध्यम झरी','🌦️'],55:['घना झरी','🌧️'],61:['हल्का वर्षा','🌦️'],63:['मध्यम वर्षा','🌧️'],65:['भारी वर्षा','🌧️'],71:['हल्का हिमपात','🌨️'],73:['मध्यम हिमपात','🌨️'],75:['भारी हिमपात','❄️'],80:['हल्का छिटपुट वर्षा','🌦️'],81:['मध्यम छिटपुट वर्षा','🌧️'],82:['तीव्र वर्षा','⛈️'],95:['मेघगर्जन','⛈️'],96:['असिनासहित मेघगर्जन','⛈️'],99:['ठूलो असिनासहित मेघगर्जन','⛈️']};
const day=['आइतबार','सोमबार','मंगलबार','बुधबार','बिहीबार','शुक्रबार','शनिबार'];
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
const weather=c=>codes[c]||['परिवर्तनशील','🌤️'];
const safe=async(url)=>{const r=await fetch(url,{cache:'no-store'});let body=null;try{body=await r.json()}catch{}if(!r.ok)throw Error(body?.reason||('HTTP '+r.status));if(body?.error)throw Error(body.reason||'API error');return body};
const show=(id,on)=>{const e=$(id);if(e)e.classList.toggle('hidden',!on)};
function localTime(s,tz){try{return new Intl.DateTimeFormat('ne-NP',{timeZone:tz||'UTC',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(s))}catch{return String(s||'').slice(11,16)}}
function hourIndex(times,tz){if(!Array.isArray(times)||!times.length)return 0;const now=new Date();let i=times.findIndex(t=>new Date(t)>=now);return i<0?times.length-1:Math.max(0,i)}
function putCurrent(d,name){const c=d.current||{},h=d.hourly||{},di=d.daily||{},tz=d.timezone||'UTC',w=weather(c.weather_code);
 set('place',name);set('updated',`अहिले · ${localTime(c.time||new Date().toISOString(),tz)} · ${tz}`);set('weatherIcon',w[1]);set('temp',fmt(c.temperature_2m)+'°');set('condition',w[0]);set('feels',fmt(c.apparent_temperature)+'°');set('high',fmt(di.temperature_2m_max?.[0])+'°');set('low',fmt(di.temperature_2m_min?.[0])+'°');set('rain',fmt(di.precipitation_probability_max?.[0])+'%');set('humidity',fmt(c.relative_humidity_2m)+'%');set('dTemp',fmt(c.temperature_2m)+'°C');set('dHum',fmt(c.relative_humidity_2m)+'%');set('wind',fmt(c.wind_speed_10m)+' km/h');set('windDir',windDir(c.wind_direction_10m));set('pressure',fmt(c.pressure_msl)+' hPa');set('cloud',fmt(c.cloud_cover)+'%');set('visibility',fmt(c.visibility/1000)+' km');set('dew',fmt(c.dew_point_2m)+'°C');set('sun','☀️ '+localTime(di.sunrise?.[0],tz)+' · 🌙 '+localTime(di.sunset?.[0],tz));set('advice',advice(c.temperature_2m,di.precipitation_probability_max?.[0],di.uv_index_max?.[0]));
 const score=Math.max(0,Math.min(100,Math.round(100-Math.max(0,Math.abs(c.temperature_2m-24)-4)*3-(di.precipitation_probability_max?.[0]||0)*.28-Math.max(0,(c.wind_speed_10m||0)-6)*3-Math.max(0,(c.cloud_cover||0)-75)*.08-Math.max(0,(di.uv_index_max?.[0]||0)-7)*2)));set('score',score+'/100');set('scoreText',score>=80?'आजको मौसम निकै सहज छ।':score>=60?'धेरैजसो कामका लागि राम्रो दिन।':score>=40?'बाहिर निस्कँदा तयारी गर्नुहोस्।':'मौसम प्रतिकूल हुन सक्छ, सावधानी अपनाउनुहोस्।');
 renderHourly(h,c,tz);renderRain(h,tz);renderDaily(di,tz);renderAQPlaceholder();
 const app=$('app');if(app)app.classList.remove('hidden');show('empty',false);
}
function windDir(v){if(v==null)return'—';return ['उत्तर','उत्तरपूर्व','पूर्व','दक्षिणपूर्व','दक्षिण','दक्षिणपश्चिम','पश्चिम','उत्तरपश्चिम'][Math.round(v/45)%8]}
function advice(t,r,u){if((r||0)>=60)return'☔ छाता/रेनकोट तयार राख्नुहोस्';if((u||0)>=7)return'🧴 घामबाट जोगिनुहोस्';if((t||0)>=32)return'💧 पानी धेरै पिउनुहोस्';if((t||0)<=10)return'🧥 न्यानो कपडा लगाउनुहोस्';return'🌤️ सामान्य बाहिरी गतिविधिका लागि ठीक'}
function renderHourly(h,c,tz){const e=$('hourly');if(!e||!Array.isArray(h.time))return;const i=hourIndex(h.time,tz);e.innerHTML=h.time.slice(i,i+24).map((t,k)=>{const j=i+k,w=weather(h.weather_code?.[j]);return `<div class="hour ${k===0?'now':''}"><small>${k===0?'अहिले':localTime(t,tz)}</small><span>${w[1]}</span><b>${fmt(h.temperature_2m?.[j])}°</b><small>☔ ${fmt(h.precipitation_probability?.[j])}%</small></div>`}).join('')}
function renderRain(h,tz){const e=$('rainChart');if(!e||!Array.isArray(h.time))return;const i=hourIndex(h.time,tz),p=(h.precipitation_probability||[]).slice(i,i+18),max=Math.max(1,...p.map(Number));e.innerHTML=p.map(v=>`<div class="rain-bar" style="height:${Math.max(5,Number(v||0)/max*100)}%"><small>${fmt(v)}%</small></div>`).join('');const first=p.findIndex(v=>Number(v)>=50);set('rainWindow',first<0?'ठूलो वर्षा संकेत छैन':`करिब ${localTime(h.time[i+first],tz)} मा वर्षा सम्भावित`)}
function renderDaily(d,tz){const e=$('daily');if(!e||!Array.isArray(d.time))return;e.innerHTML=d.time.map((t,i)=>{const w=weather(d.weather_code?.[i]);return `<div class="day"><b>${i===0?'आज':i===1?'भोलि':day[new Date(t+'T12:00:00').getDay()]}</b><span class="wx">${w[1]}</span><span>${w[0]}</span><span><b>${fmt(d.temperature_2m_max?.[i])}°</b> / ${fmt(d.temperature_2m_min?.[i])}° · ☔ ${fmt(d.precipitation_probability_max?.[i])}%</span></div>`}).join('')}
function renderAQPlaceholder(){set('aqi','—');set('pm25','—');set('pm10','—');}
async function loadAQ(lat,lon,tz){try{const a=await safe(`${AQ}?latitude=${lat}&longitude=${lon}&timezone=${encodeURIComponent(tz||'auto')}&hourly=pm2_5,pm10,european_aqi&forecast_days=2`);const h=a.hourly||{},i=hourIndex(h.time,tz),aq=h.european_aqi?.[i],p25=h.pm2_5?.[i],p10=h.pm10?.[i];set('aqi',fmt(aq));set('pm25',fmt(p25));set('pm10',fmt(p10))}catch(e){set('aqi','उपलब्ध छैन');set('pm25','उपलब्ध छैन');set('pm10','उपलब्ध छैन')}}
async function load(lat,lon,name,add=true){show('empty',false);show('loading',true);const cleanLat=Number(lat),cleanLon=Number(lon);if(!Number.isFinite(cleanLat)||!Number.isFinite(cleanLon)){show('loading',false);return showError('स्थानको coordinates अमान्य छन्।')}
 try{const q=new URLSearchParams({latitude:cleanLat.toFixed(6),longitude:cleanLon.toFixed(6),timezone:'auto',forecast_days:'7',current:'temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,rain,weather_code,cloud_cover,pressure_msl,surface_pressure,wind_speed_10m,wind_direction_10m',hourly:'temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation_probability,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_direction_10m,visibility,uv_index,pressure_msl,surface_pressure',daily:'weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,precipitation_sum,rain_sum,precipitation_probability_max,wind_speed_10m_max,uv_index_max,sunrise,sunset'});const d=await safe(`${API}?${q}`);putCurrent(d,name||'चयन गरिएको स्थान');loadAQ(cleanLat,cleanLon,d.timezone);localStorage.setItem('mausam_last',JSON.stringify({lat:cleanLat,lon:cleanLon,name:name||'स्थान'}));show('loading',false)}catch(e){show('loading',false);showError(e.message||'API request failed');console.error('Mausam weather error:',e)}}
function showError(reason){const app=$('app');if(app)app.classList.add('hidden');const empty=$('empty');if(empty){empty.classList.remove('hidden');const msg=empty.querySelector('[data-error],.error-message,p,small');if(msg)msg.textContent='मौसमको डाटा ल्याउन सकिएन। '+reason}else alert('मौसमको डाटा ल्याउन सकिएन। '+reason)}
async function search(q){q=String(q||'').trim();if(!q)return;const box=$('results');if(box){box.innerHTML='<div class="result">खोज्दै…</div>';box.style.display='block'}try{let r=await safe(`${GEO}?q=${encodeURIComponent(q+', Nepal')}&format=json&limit=7&accept-language=ne`);if(!Array.isArray(r)||!r.length)r=await safe(`${GEO}?q=${encodeURIComponent(q)}&format=json&limit=7&accept-language=ne`);if(box)box.innerHTML=r.length?r.map(x=>`<div class="result" data-lat="${x.lat}" data-lon="${x.lon}" data-name="${(x.display_name||q).split(',')[0]}"><b>${x.name||q}</b><small>${x.display_name||''}</small></div>`).join(''):'<div class="result">स्थान भेटिएन।</div>';if(box)box.querySelectorAll('[data-lat]').forEach(x=>x.onclick=()=>{box.style.display='none';load(x.dataset.lat,x.dataset.lon,x.dataset.name)})}catch(e){if(box)box.innerHTML='<div class="result">स्थान खोज्न सकिएन।</div>';console.error(e)}}
window.load=load;window.search=search;window.loadWeather=load;window.searchWeather=search;
function bind(){const input=document.querySelector('input[type="search"],input[placeholder*="खोज"],input[placeholder*="स्थान"]');if(input){input.addEventListener('keydown',e=>{if(e.key==='Enter')search(input.value)});const form=input.closest('form');if(form)form.addEventListener('submit',e=>{e.preventDefault();search(input.value)})}document.querySelectorAll('[data-lat][data-lon]').forEach(e=>{if(!e.dataset.bound)e.addEventListener('click',()=>load(e.dataset.lat,e.dataset.lon,e.dataset.name||e.textContent.trim())),e.dataset.bound='1'});const last=localStorage.getItem('mausam_last');if(last){try{const x=JSON.parse(last);load(x.lat,x.lon,x.name,false)}catch{}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();