(function(){'use strict';
const DIRECT='https://www.dhm.gov.np';
const PROXY='https://api.allorigins.win/raw?url=';
const THRESHOLDS={oneHour:60,threeHour:80,sixHour:100,twelveHour:120,twentyFourHour:140};
let LAST_SOURCE='UNAVAILABLE',LAST_CHECKED=null;
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
async function get(url){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);LAST_SOURCE='LIVE';LAST_CHECKED=new Date().toISOString();return await r.text()}catch(e){const r=await fetch(PROXY+encodeURIComponent(url),{cache:'no-store'});if(!r.ok)throw e;LAST_SOURCE='PROXY';LAST_CHECKED=new Date().toISOString();return await r.text()}}
function doc(html){return new DOMParser().parseFromString(html,'text/html')}
function clean(s){return(s||'').replace(/\s+/g,' ').trim()}
function tables(d){return[...d.querySelectorAll('table')].filter(t=>t.querySelectorAll('tr').length>1)}
function cells(tr){return[...tr.querySelectorAll('th,td')].map(x=>clean(x.textContent))}
function tableRows(d,min){const rows=[];for(const t of tables(d))for(const tr of [...t.querySelectorAll('tr')]){const c=cells(tr);if(c.length>=min&&/\d/.test(c.join(' ')))rows.push(c)}return rows}
function riverStations(d){return tableRows(d,7).map(c=>{const level=parseFloat(c[4]),warning=parseFloat(c[5]),danger=parseFloat(c[6]);if(!Number.isFinite(level)||!Number.isFinite(warning)||!Number.isFinite(danger))return null;return {stationNo:c[0],basin:c[1],station:c[2],district:c[3],waterLevel:level,warningLevel:warning,dangerLevel:danger,trend:c[7]||'',status:level>=danger?'danger':level>=warning?'warning':'normal'}}).filter(Boolean)}
function rainfallStations(d){return tableRows(d,6).map(c=>{const nums=c.slice(4).map(v=>parseFloat(String(v).replace(/,/g,''))).filter(Number.isFinite);return {stationNo:c[0]||'',basin:c[1]||'',station:c[2]||'',district:c[3]||'',oneHour:nums[0],threeHour:nums[1],sixHour:nums[2],twelveHour:nums[3],twentyFourHour:nums[4],raw:c}}).filter(x=>Number.isFinite(x.oneHour)||Number.isFinite(x.twentyFourHour))}
function renderTable(el,headers,rows){el.innerHTML='<div class="table-scroll"><table class="hydro-table"><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function setStatus(el,msg){if(el)el.innerHTML='<div class="status">'+esc(msg)+'</div>'}
async function rainfall(){const out=document.getElementById('data');setStatus(out,'DHM वर्षा डाटा ल्याउँदैछ…');try{const d=doc(await get(DIRECT+'/hydrology/rainfall-watch-map'));const rows=tableRows(d,4);if(!rows.length){setStatus(out,'DHM को वर्षा तालिका अहिले dynamic रूपमा लोड भइरहेको छ।');return}renderTable(out,['डाटा','डाटा','डाटा','डाटा','डाटा','स्थिति'],rows.slice(0,300))}catch(e){setStatus(out,'DHM वर्षा डाटा ल्याउन सकिएन। आधिकारिक DHM पृष्ठ खोल्नुहोस्।')}}
async function rivers(){const out=document.getElementById('data');setStatus(out,'DHM नदी डाटा ल्याउँदैछ…');try{const d=doc(await get(DIRECT+'/hydrology/river-watch'));const rows=tableRows(d,6);if(!rows.length){setStatus(out,'DHM को नदी तालिका अहिले dynamic रूपमा लोड भइरहेको छ।');return}renderTable(out,['स्टेशन नं.','जलाधार','स्टेशन','जिल्ला','जलसतह','चेतावनी/खतरा','ट्रेन्ड/स्थिति'],rows.slice(0,300))}catch(e){setStatus(out,'DHM नदी डाटा ल्याउन सकिएन। आधिकारिक DHM पृष्ठ खोल्नुहोस्।')}}
async function current(){const out=document.getElementById('data');setStatus(out,'DHM को official status ल्याउँदैछ…');try{const d=doc(await get(DIRECT+'/?locale=en'));const text=clean(d.body.textContent);const rain=text.match(/Max 24hr:\s*([\s\S]*?)(?=Narayani at Devghat)/i);const rivers=[...text.matchAll(/(Narayani at Devghat|Karnali at Chisapani|Kankai River at Mainachuli|Babai at Chepang|Mahakali at Parigaon)\s*WL:\s*([^ ]+) m WR:\s*([^ ]+) m DL:\s*([^ ]+) m/gi)];const warning=/WARNING\(S\) IN EFFECT/i.test(text);const cards=[];const max24=rain?parseFloat(String(rain[1]).replace(/,/g,'')):NaN;if(rain)cards.push(['२४ घण्टाको अधिकतम वर्षा',rain[1]]);rivers.forEach(m=>cards.push([m[1],'जलसतह '+m[2]+' m · चेतावनी '+m[3]+' m · खतरा '+m[4]+' m']));if(!cards.length){setStatus(out,'DHM official status उपलब्ध भएन।');return}out.max24=max24;out.warning=warning;out.rivers=rivers.map(m=>({station:m[1],waterLevel:m[2],warningLevel:m[3],dangerLevel:m[4]}));out.innerHTML='<div class="summary-grid">'+cards.map(c=>'<div class="summary"><small>'+esc(c[0])+'</small><strong>'+esc(c[1])+'</strong></div>').join('')+'</div><p class="status">'+(warning?'⚠️ DHM अनुसार warning(s) in effect देखिएको छ।':'ℹ️ DHM official monitoring status पढियो।')+'</p>'}catch(e){setStatus(out,'DHM official status ल्याउन सकिएन।')}}
async function national(){const out={rainfall:[],rivers:[],source:'DHM',thresholds:THRESHOLDS};try{out.rainfall=tableRows(doc(await get(DIRECT+'/hydrology/rainfall-watch-map')),4)}catch{}try{out.rivers=tableRows(doc(await get(DIRECT+'/hydrology/river-watch')),6)}catch{}return out}
async function district(name){const out={rainfall:[],rivers:[],source:'DHM',thresholds:THRESHOLDS};const key=String(name||'').trim().toLocaleLowerCase('ne');try{out.rainfall=tableRows(doc(await get(DIRECT+'/hydrology/rainfall-watch-map')),4).filter(c=>c.some(x=>x.toLocaleLowerCase('ne').includes(key)))}catch{}try{out.rivers=tableRows(doc(await get(DIRECT+'/hydrology/river-watch')),6).filter(c=>c.some(x=>x.toLocaleLowerCase('ne').includes(key)))}catch{}return out}
window.HydrologyData={rainfall,rivers,current,national,district,THRESHOLDS,SOURCE:DIRECT};
})();