(()=>{'use strict';
const points=[
['ताप्लेजुङ',27.35,87.67],['पाँचथर',27.15,87.77],['इलाम',26.91,87.93],['झापा',26.55,87.81],['मोरङ',26.45,87.27],['सुनसरी',26.62,87.15],['धनकुटा',26.98,87.34],['तेह्रथुम',27.13,87.55],['संखुवासभा',27.38,87.21],['भोजपुर',27.18,87.05],['सोलुखुम्बु',27.31,86.72],['ओखलढुंगा',27.31,86.50],['खोटाङ',27.20,86.80],['उदयपुर',26.80,86.70],['सप्तरी',26.52,86.75],['सिराहा',26.65,86.20],['धनुषा',26.73,85.92],['महोत्तरी',26.87,85.78],['सर्लाही',26.96,85.56],['रौतहट',27.00,85.28],['बारा',27.02,84.87],['पर्सा',27.00,84.88],['दोलखा',27.67,86.05],['रामेछाप',27.33,86.09],['सिन्धुली',27.27,85.97],['काभ्रेपलाञ्चोक',27.63,85.52],['सिन्धुपाल्चोक',27.95,85.68],['रसुवा',28.12,85.30],['नुवाकोट',27.91,85.17],['धादिङ',27.87,84.90],['काठमाडौं',27.72,85.32],['भक्तपुर',27.67,85.43],['ललितपुर',27.66,85.32],['मकवानपुर',27.43,85.03],['चितवन',27.53,84.35],['गोरखा',28.00,84.63],['मनाङ',28.67,84.02],['मुस्ताङ',28.99,83.85],['म्याग्दी',28.35,83.57],['कास्की',28.21,83.99],['लमजुङ',28.28,84.36],['तनहुँ',27.95,84.25],['नवलपुर',27.70,84.12],['स्याङ्जा',28.09,83.82],['पर्वत',28.22,83.69],['बागलुङ',28.27,83.59],['रुकुम पूर्व',28.63,82.63],['रोल्पा',28.30,82.65],['प्यूठान',28.10,82.80],['गुल्मी',28.08,83.25],['अर्घाखाँची',27.98,83.13],['पाल्पा',27.87,83.55],['नवलपरासी पश्चिम',27.53,83.67],['रुपन्देही',27.50,83.45],['कपिलवस्तु',27.55,83.05],['दाङ',28.05,82.49],['बाँके',28.05,81.62],['बर्दिया',28.30,81.35],['डोल्पा',29.03,82.72],['मुगु',29.65,82.17],['हुम्ला',29.97,81.82],['जुम्ला',29.27,82.18],['कालिकोट',29.13,81.60],['दैलेख',28.84,81.71],['जाजरकोट',28.70,82.20],['रुकुम पश्चिम',28.63,82.45],['सल्यान',28.38,82.15],['सुर्खेत',28.60,81.63],['बझाङ',29.55,81.20],['बाजुरा',29.50,81.50],['अछाम',29.05,81.25],['डोटी',29.27,80.95],['डडेलधुरा',29.30,80.58],['बैतडी',29.52,80.43],['दार्चुला',29.85,80.55],['कञ्चनपुर',28.83,80.32],['कैलाली',28.70,80.60]
];
window.NEPAL_WEATHER_POINTS=points;const W='https://api.open-meteo.com/v1/forecast',AQ='https://air-quality-api.open-meteo.com/v1/air-quality';
const $=id=>document.getElementById(id),nf=v=>v==null||Number.isNaN(Number(v))?'—':new Intl.NumberFormat('ne-NP',{maximumFractionDigits:0}).format(Math.round(Number(v)));
let data=[],busy=false,filter='hot';
const icons={hot:'🔥',cold:'🧊',rain:'🌧️',uv:'☀️',aqi:'🫧',wind:'💨'};
const labels={hot:'सबैभन्दा तातो',cold:'सबैभन्दा चिसो',rain:'वर्षा सम्भावना',uv:'उच्च UV',aqi:'खराब AQI',wind:'तेज हावा'};
function section(){if($('intelligence'))return;const s=document.createElement('section');s.id='intelligence';s.className='card intelligence';s.innerHTML=`<div class="section-head"><div><h2>🌦️ नेपाल Weather Intelligence Center</h2><p class="muted">७७ जिल्ला केन्द्र आसपासको Open-Meteo डाटाबाट स्मार्ट संकेत। सरकारी चेतावनी होइन।</p></div><button id="scanDistricts" class="text-btn">↻ पुनः स्क्यान</button></div><div class="intel-status"><span id="intelProgress">तयार</span><span id="intelUpdated">—</span></div><div id="intelSummary" class="intel-summary"><div><b id="intelScanned">०/७७</b><small>जिल्ला स्क्यान</small></div><div><b id="intelCritical">०</b><small>🔴 गम्भीर संकेत</small></div><div><b id="intelWarning">०</b><small>🟠 चेतावनी संकेत</small></div><div><b id="intelAdvisory">०</b><small>🟡 सावधानी</small></div><div><b id="intelNormal">०</b><small>🟢 सामान्य</small></div><div><b id="intelRain">०</b><small>☔ वर्षा ≥ ६०%</small></div><div><b id="intelWind">०</b><small>💨 हावा ≥ ३५</small></div></div><div class="intel-tabs">${Object.entries(labels).map(([k,v])=>`<button data-filter="${k}" class="${k==='hot'?'active':''}">${icons[k]} ${v}</button>`).join('')}</div><div id="intelGrid" class="intel-grid"></div>`;const target=$('districtExplorer');target?.insertAdjacentElement('afterend',s);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('scanDistricts').onclick=scan}
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}
function batches(arr,n){const out=[];for(let i=0;i<arr.length;i+=n)out.push(arr.slice(i,i+n));return out}
function parseLocations(result){return Array.isArray(result)?result:[result]}
async function scan(){if(busy)return;busy=true;data=[];render();const groups=batches(points,12);let done=0;for(const group of groups){const lats=group.map(p=>p[1]).join(','),lons=group.map(p=>p[2]).join(',');const wp=new URLSearchParams({latitude:lats,longitude:lons,timezone:'Asia/Kathmandu',forecast_days:'1',current:'temperature_2m,wind_speed_10m,weather_code',daily:'temperature_2m_max,temperature_2m_min,precipitation_probability_max,uv_index_max,wind_speed_10m_max',mausam_scan:'1'});const ap=new URLSearchParams({latitude:lats,longitude:lons,timezone:'Asia/Kathmandu',forecast_days:'1',hourly:'pm2_5,pm10,european_aqi',mausam_scan:'1'});try{const [wr,ar]=await Promise.allSettled([get(W+'?'+wp),get(AQ+'?'+ap)]);const ws=wr.status==='fulfilled'?parseLocations(wr.value):[],as=ar.status==='fulfilled'?parseLocations(ar.value):[];group.forEach((p,i)=>{const w=ws[i]||{},a=as[i]||{},ah=a.hourly||{};let idx=0;const times=ah.time||[];if(times.length){const now=Date.now();const found=times.findIndex(t=>new Date(t).getTime()>=now);idx=found<0?0:found}data.push({name:p[0],lat:p[1],lon:p[2],temp:w.current?.temperature_2m,wind:w.current?.wind_speed_10m,rain:w.daily?.precipitation_probability_max?.[0],uv:w.daily?.uv_index_max?.[0],max:w.daily?.temperature_2m_max?.[0],min:w.daily?.temperature_2m_min?.[0],aqi:ah.european_aqi?.[idx]??null,code:w.current?.weather_code})})}catch{}done+=group.length;$('intelProgress').textContent=`जिल्ला स्क्यान हुँदैछ… ${nf(Math.min(done,points.length))}/${nf(points.length)}`;render();await new Promise(r=>setTimeout(r,120))}data=data.filter(x=>x.temp!=null||x.max!=null||x.rain!=null||x.aqi!=null);busy=false;$('intelProgress').textContent=`${nf(data.length)}/${nf(points.length)} जिल्ला सफल`;$('intelUpdated').textContent='अन्तिम स्क्यान: '+new Date().toLocaleTimeString('ne-NP',{hour:'numeric',minute:'2-digit'});render();try{localStorage.setItem('mausam_intel',JSON.stringify({at:Date.now(),data}))}catch{}}
function sort(){const a=[...data];if(filter==='hot')return a.sort((x,y)=>(y.temp??-999)-(x.temp??-999));if(filter==='cold')return a.sort((x,y)=>(x.temp??999)-(y.temp??999));if(filter==='rain')return a.sort((x,y)=>(y.rain??-1)-(x.rain??-1));if(filter==='uv')return a.sort((x,y)=>(y.uv??-1)-(x.uv??-1));if(filter==='aqi')return a.sort((x,y)=>(y.aqi??-1)-(x.aqi??-1));return a.sort((x,y)=>(y.wind??-1)-(x.wind??-1))}
function value(x){if(filter==='hot'||filter==='cold')return `${nf(x.temp)}°C`;if(filter==='rain')return `${nf(x.rain)}%`;if(filter==='uv')return nf(x.uv);if(filter==='aqi')return nf(x.aqi);return `${nf(x.wind)} km/h`}
function note(x){if(filter==='rain')return x.rain>=60?'छाता/रेनकोट तयार':'वर्षा सम्भावना कम';if(filter==='aqi')return x.aqi==null?'AQI उपलब्ध छैन':x.aqi>=100?'हावामा सावधानी':'हावा सामान्यतर्फ';if(filter==='wind')return x.wind>=35?'यात्रामा सावधानी':'हावा सामान्य';if(filter==='uv')return x.uv>=7?'दिउँसो घामबाट जोगिनुहोस्':'UV सामान्य';if(filter==='hot')return x.temp>=32?'गर्मी सावधानी':'तापक्रम सामान्य';return x.temp<=10?'न्यानो कपडा':'चिसो सावधानी'}
function select(name){const input=$('search');if(!input)return;input.value=name;input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));window.scrollTo({top:0,behavior:'smooth'})}
function updateSummary(){const ok=data.filter(x=>x.temp!=null||x.max!=null||x.rain!=null||x.aqi!=null);let critical=0,warning=0,advisory=0,normal=0,rain=0,wind=0;ok.forEach(x=>{let r=0;if((x.rain??0)>=90)r+=45;else if((x.rain??0)>=70)r+=30;else if((x.rain??0)>=50)r+=15;if((x.wind??0)>=60)r+=30;else if((x.wind??0)>=45)r+=18;if((x.temp??0)>=40)r+=25;else if((x.temp??0)>=35)r+=15;if(r>=70)critical++;else if(r>=45)warning++;else if(r>=20)advisory++;else normal++;if((x.rain??0)>=60)rain++;if((x.wind??0)>=35)wind++});if($('intelScanned'))$('intelScanned').textContent=nf(ok.length)+'/७७';if($('intelCritical'))$('intelCritical').textContent=nf(critical);if($('intelWarning'))$('intelWarning').textContent=nf(warning);if($('intelAdvisory'))$('intelAdvisory').textContent=nf(advisory);if($('intelNormal'))$('intelNormal').textContent=nf(normal);if($('intelRain'))$('intelRain').textContent=nf(rain);if($('intelWind'))$('intelWind').textContent=nf(wind)}
function render(){const grid=$('intelGrid');if(!grid)return;updateSummary();if(!data.length){grid.innerHTML='<div class="intel-empty">डेटा सङ्कलन हुँदैछ…</div>';return}grid.innerHTML=sort().slice(0,6).map((x,i)=>`<button class="intel-card" data-name="${x.name}"><span class="rank">${nf(i+1)}</span><div><b>${icons[filter]} ${x.name}</b><small>${labels[filter]} · ${note(x)}</small></div><strong>${value(x)}</strong></button>`).join('');grid.querySelectorAll('.intel-card').forEach(b=>b.onclick=()=>select(b.dataset.name))}
function boot(){section();let saved;try{saved=JSON.parse(localStorage.getItem('mausam_intel')||'null')}catch{}if(saved?.data?.length&&Date.now()-saved.at<15*60*1000){data=saved.data;$('intelProgress').textContent=`${nf(data.length)}/७७ जिल्ला · क्यास`;$('intelUpdated').textContent='१५ मिनेटभित्रको डाटा';render()}else scan()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();