(()=>{'use strict';
const GEOJSON_URL='https://raw.githubusercontent.com/Acesmndr/nepal-geojson/master/generated-geojson/nepal-with-districts-acesmndr.geojson';
const names={
JHAPA:'झापा',ILAM:'इलाम',PANCHTHAR:'पाँचथर',TAPLEJUNG:'ताप्लेजुङ',MORANG:'मोरङ',SUNSARI:'सुनसरी',DHANKUTA:'धनकुटा',TERHATHUM:'तेह्रथुम',SANKHUWASABHA:'संखुवासभा',BHOJPUR:'भोजपुर',SOLUKHUMBU:'सोलुखुम्बु',OKHALDHUNGA:'ओखलढुंगा',KHOTANG:'खोटाङ',UDAYAPUR:'उदयपुर',SAPTARI:'सप्तरी',SIRAHA:'सिराहा',DHANUSHA:'धनुषा',MAHOTTARI:'महोत्तरी',SARLAHI:'सर्लाही',RAUTAHAT:'रौतहट',BARA:'बारा',PARSA:'पर्सा',DOLAKHA:'दोलखा',RAMECHHAP:'रामेछाप',SINDHULI:'सिन्धुली',KAVREPALANCHOK:'काभ्रेपलाञ्चोक',SINDHUPALCHOK:'सिन्धुपाल्चोक',RUSUWA:'रसुवा',NUWAKOT:'नुवाकोट',DHADING:'धादिङ',KATHMANDU:'काठमाडौं',BHAKTAPUR:'भक्तपुर',LALITPUR:'ललितपुर',MAKWANPUR:'मकवानपुर',CHITWAN:'चितवन',GORKHA:'गोरखा',MANANG:'मनाङ',MUSTANG:'मुस्ताङ',MYAGDI:'म्याग्दी',KASKI:'कास्की',LAMJUNG:'लमजुङ',TANAHU:'तनहुँ',NAWALPARASI_EAST:'नवलपुर',SYANGJA:'स्याङ्जा',PARBAT:'पर्वत',BAGLUNG:'बागलुङ',RUKUM_EAST:'रुकुम पूर्व',ROLPA:'रोल्पा',PYUTHAN:'प्यूठान',GULMI:'गुल्मी',ARGHAKHANCHI:'अर्घाखाँची',PALPA:'पाल्पा',NAWALPARASI_WEST:'नवलपरासी पश्चिम',RUPANDEHI:'रुपन्देही',KAPILVASTU:'कपिलवस्तु',DANG:'दाङ',BANKE:'बाँके',BARDIYA:'बर्दिया',DOLPA:'डोल्पा',MUGU:'मुगु',HUMLA:'हुम्ला',JUMLA:'जुम्ला',KALIKOT:'कालिकोट',DAILEKH:'दैलेख',JAJARKOT:'जाजरकोट',RUKUM_WEST:'रुकुम पश्चिम',SALYAN:'सल्यान',SURKHET:'सुर्खेत',BAJHANG:'बझाङ',BAJURA:'बाजुरा',ACHHAM:'अछाम',DOTI:'डोटी',DADELDHURA:'डडेलधुरा',BAITADI:'बैतडी',DARCHULA:'दार्चुला',KANCHANPUR:'कञ्चनपुर',KAILALI:'कैलाली'
};
const el=id=>document.getElementById(id);let layer='temp',geo=null,rows=[],provinceFilter='all',searchTerm='';const provinceDistricts={"1":["JHAPA","ILAM","PANCHTHAR","TAPLEJUNG","MORANG","SUNSARI","DHANKUTA","TERHATHUM","SANKHUWASABHA","BHOJPUR","SOLUKHUMBU","OKHALDHUNGA","KHOTANG","UDAYAPUR"],"2":["SAPTARI","SIRAHA","DHANUSHA","MAHOTTARI","SARLAHI","RAUTAHAT","BARA","PARSA"],"3":["DOLAKHA","RAMECHHAP","SINDHULI","KAVREPALANCHOK","SINDHUPALCHOK","RUSUWA","NUWAKOT","DHADING","KATHMANDU","BHAKTAPUR","LALITPUR","MAKWANPUR","CHITWAN"],"4":["GORKHA","MANANG","MUSTANG","MYAGDI","KASKI","LAMJUNG","TANAHU","NAWALPARASI_EAST","SYANGJA","PARBAT","BAGLUNG"],"5":["RUKUM_EAST","ROLPA","PYUTHAN","GULMI","ARGHAKHANCHI","PALPA","NAWALPARASI_WEST","RUPANDEHI","KAPILVASTU","DANG","BANKE","BARDIYA"],"6":["DOLPA","MUGU","HUMLA","JUMLA","KALIKOT","DAILEKH","JAJARKOT","RUKUM_WEST","SALYAN","SURKHET"],"7":["BAJHANG","BAJURA","ACHHAM","DOTI","DADELDHURA","BAITADI","DARCHULA","KANCHANPUR","KAILALI"]};const districtProvince=Object.fromEntries(Object.entries(provinceDistricts).flatMap(([p,ds])=>ds.map(d=>[d,p])));const provinceNames={all:'सबै प्रदेश',1:'कोशी प्रदेश',2:'मधेश प्रदेश',3:'बागमती प्रदेश',4:'गण्डकी प्रदेश',5:'लुम्बिनी प्रदेश',6:'कर्णाली प्रदेश',7:'सुदूरपश्चिम प्रदेश'};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function flatCoords(g){const out=[];const walk=x=>Array.isArray(x[0])?x.forEach(walk):out.push(x);walk(g.coordinates);return out}
function centroid(f){const c=flatCoords(f.geometry);let x=0,y=0;c.forEach(p=>{x+=p[0];y+=p[1]});return [y/c.length,x/c.length]}
function bounds(features){let a=Infinity,b=-Infinity,c=Infinity,d=-Infinity;features.forEach(f=>flatCoords(f.geometry).forEach(p=>{a=Math.min(a,p[0]);b=Math.max(b,p[0]);c=Math.min(c,p[1]);d=Math.max(d,p[1])}));return [a,b,c,d]}
function path(g,box){const [minX,maxX,minY,maxY]=box, sx=980/(maxX-minX), sy=720/(maxY-minY), X=x=>((x-minX)*sx+10).toFixed(1), Y=y=>(730-(y-minY)*sy).toFixed(1);const ring=r=>r.map((p,i)=>(i?'L':'M')+X(p[0])+' '+Y(p[1])).join(' ')+' Z';return g.type==='Polygon'?g.coordinates.map(ring).join(' '):g.coordinates.map(p=>p.map(ring).join(' ')).join(' ')}
function color(v,type){if(type==='temp'){if(v>=35)return '#ef4444';if(v>=30)return '#f97316';if(v>=25)return '#f59e0b';if(v>=18)return '#22c55e';if(v>=10)return '#38bdf8';return '#2563eb'}if(type==='rain'){if(v>=80)return '#1d4ed8';if(v>=60)return '#3b82f6';if(v>=30)return '#60a5fa';if(v>=10)return '#93c5fd';return '#dbeafe'}if(type==='wind'){if(v>=60)return '#7c3aed';if(v>=40)return '#a855f7';if(v>=25)return '#c084fc';if(v>=10)return '#ddd6fe';return '#f3e8ff'}if(type==='aqi'){if(v>=200)return '#7f1d1d';if(v>=150)return '#dc2626';if(v>=100)return '#f97316';if(v>=50)return '#facc15';return '#86efac'}return '#dbeafe'}
function weatherLabel(c){const m={0:['☀️','सफा आकाश'],1:['🌤️','मुख्यतः सफा'],2:['⛅','आंशिक बदली'],3:['☁️','बादल लागेको'],45:['🌫️','कुहिरो'],48:['🌫️','बाक्लो कुहिरो'],51:['🌦️','हल्का झरी'],53:['🌦️','झरी'],55:['🌧️','घना झरी'],61:['🌦️','हल्का वर्षा'],63:['🌧️','वर्षा'],65:['🌧️','भारी वर्षा'],71:['🌨️','हल्का हिमपात'],73:['🌨️','हिमपात'],75:['❄️','भारी हिमपात'],80:['🌦️','वर्षाका छिटा'],81:['🌧️','वर्षाका छिटा'],82:['⛈️','भारी वर्षाका छिटा'],95:['⛈️','चट्याङसहितको हुरी'],96:['⛈️','चट्याङ/असिना'],99:['⛈️','चट्याङ/असिना']}[c]||['🌤️','मौसम'];return {icon:m[0],text:m[1]}};function value(r){return layer==='temp'?r.t:layer==='rain'?r.r:layer==='wind'?r.w:r.a}
function label(r){const v=value(r);return layer==='temp'?v.toFixed(1)+'°C':layer==='rain'?Math.round(v)+'%':layer==='wind'?Math.round(v)+' km/h':r.a?Math.round(v):'—'}
function render(){if(!geo||!rows.length)return;const map=new Map(rows.map(r=>[r.e,r]));const features=geo.features.filter(f=>(provinceFilter==='all'||String(districtProvince[f.properties.DISTRICT]||'')===provinceFilter)&&(!searchTerm||String(names[f.properties.DISTRICT]||f.properties.DISTRICT).toLowerCase().includes(searchTerm.toLowerCase())));const svg=el('districtMap');const box=bounds(features.length?features:geo.features);svg.innerHTML='<svg class="nepal-weather-svg" viewBox="0 0 1000 760" role="img" aria-label="नेपाल ७७ जिल्ला मौसम नक्सा">'+features.map(f=>{const e=f.properties.DISTRICT;const r=map.get(e);const p=path(f.geometry,box);const [lat,lon]=centroid(f);const v=r?value(r):0;return '<path class="district-shape" data-district="'+esc(e)+'" d="'+p+'" fill="'+color(v,layer)+'" tabindex="0"><title>'+esc(names[e]||e)+' · '+esc(label(r||{t:0,r:0,w:0,a:0,h:0,p:0,code:0}))+'</title></path>'}).join('')+'</svg><div class="map-tooltip" id="mapTooltip"></div>';const visibleRows=(provinceFilter==='all'?rows:rows.filter(r=>String(districtProvince[r.e]||'')===provinceFilter)).filter(r=>!searchTerm||r.n.toLowerCase().includes(searchTerm.toLowerCase()));const temps=visibleRows.map(r=>r.t).filter(Number.isFinite),rains=visibleRows.map(r=>r.r).filter(Number.isFinite);const avg=temps.length?(temps.reduce((a,b)=>a+b,0)/temps.length).toFixed(1):'—';const maxRain=rains.length?Math.round(Math.max(...rains)):'—';const hottest=visibleRows.slice().sort((a,b)=>b.t-a.t)[0];el('mapSummary').innerHTML='<div><small>जिल्ला</small><b>'+visibleRows.length+'</b></div><div><small>औसत तापक्रम</small><b>'+avg+'°C</b></div><div><small>अधिकतम वर्षा सम्भावना</small><b>'+maxRain+'%</b></div><div><small>सबैभन्दा तातो</small><b>'+esc(hottest?.n||'—')+'</b></div>';el('mapLegend').innerHTML=(provinceFilter!=='all'?'📍 '+esc(provinceNames[provinceFilter])+' · ':'')+(layer==='temp'?'🔵 चिसो → 🟢 सामान्य → 🔴 तातो':layer==='rain'?'☔ कम → मध्यम → भारी वर्षा सम्भावना':layer==='wind'?'💨 कम → मध्यम → तेज हावा':'😷 🟢 राम्रो → 🟡 मध्यम → 🔴 अस्वस्थ');renderLocationOverlay(box);el('mapStatus').textContent=(visibleRows.length?'':'कुनै जिल्ला भेटिएन · ')+(provinceFilter==='all'?(searchTerm?visibleRows.length+' जिल्ला':'७७ जिल्ला'):visibleRows.length+' जिल्ला')+' · '+(layer==='aqi'?'AQI':'live weather')+' · जिल्लामा ट्याप गर्नुहोस्'}
async function forecastBatch(items){const lats=items.map(x=>x.lat).join(','),lons=items.map(x=>x.lon).join(',');const u='https://api.open-meteo.com/v1/forecast?latitude='+lats+'&longitude='+lons+'&current=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,weather_code&hourly=precipitation_probability&forecast_days=1';const data=await fetch(u).then(r=>r.json());return Array.isArray(data)?data:[data]}
async function loadWeather(){for(let i=0;i<geo.features.length;i+=10){const batch=geo.features.slice(i,i+10).map(f=>{const [lat,lon]=centroid(f);return {e:f.properties.DISTRICT,lat,lon}});try{const data=await forecastBatch(batch);data.forEach((j,k)=>{const b=batch[k];rows.push({e:b.e,n:names[b.e]||b.e,lat:b.lat,lon:b.lon,t:+j?.current?.temperature_2m||0,r:Array.isArray(j?.hourly?.precipitation_probability)?Math.max(...j.hourly.precipitation_probability.slice(0,24).map(Number).filter(Number.isFinite),0):0,w:+j?.current?.wind_speed_10m||0,a:0,h:+j?.current?.relative_humidity_2m||0,p:+j?.current?.precipitation||0,code:+j?.current?.weather_code||0})})}catch{batch.forEach(b=>rows.push({...b,n:names[b.e]||b.e,t:0,r:0,w:0,a:0}))}el('mapStatus').textContent=Math.min(i+10,geo.features.length)+' / ७७ जिल्लाको मौसम तयार हुँदैछ…';render()}}
async function loadAqi(){el('mapStatus').textContent='७७ जिल्लाको AQI ल्याउँदैछ…';for(let i=0;i<rows.length;i+=10){const batch=rows.slice(i,i+10);try{const u='https://air-quality-api.open-meteo.com/v1/air-quality?latitude='+batch.map(x=>x.lat).join(',')+'&longitude='+batch.map(x=>x.lon).join(',')+'&current=us_aqi&forecast_days=1';const data=await fetch(u).then(r=>r.json());const arr=Array.isArray(data)?data:[data];arr.forEach((j,k)=>batch[k].a=+j?.current?.us_aqi||0)}catch{}render()}}

function haversine(lat1,lon1,lat2,lon2){const R=6371,rad=Math.PI/180,dLat=(lat2-lat1)*rad,dLon=(lon2-lon1)*rad;const a=Math.sin(dLat/2)**2+Math.cos(lat1*rad)*Math.cos(lat2*rad)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
let userLocation=null,nearestDistrict=null;
function findNearestDistrict(lat,lon){return rows.reduce((best,r)=>{const distance=haversine(lat,lon,r.lat,r.lon);return !best||distance<best.distance?{...r,distance}:best},null)}
function highlightNearest(){document.querySelectorAll('.district-shape.nearest-district').forEach(x=>x.classList.remove('nearest-district'));if(!nearestDistrict)return;const p=document.querySelector('.district-shape[data-district="'+CSS.escape(nearestDistrict.e)+'"]');if(p)p.classList.add('nearest-district')}
function renderMyLocation(){const box=el('myLocationStatus');if(!box||!nearestDistrict)return;const r=nearestDistrict,c=weatherLabel(r.code);box.hidden=false;box.innerHTML='<div class="my-location-head"><span>📍</span><div><small>तपाईंको स्थानबाट नजिकको जिल्ला</small><h2>'+esc(r.n)+'</h2></div></div><div class="my-location-metrics"><div><small>दूरी</small><b>'+r.distance.toFixed(1)+' km</b></div><div><small>तापक्रम</small><b>'+r.t.toFixed(1)+'°C</b></div><div><small>अवस्था</small><b>'+c.icon+' '+esc(c.text)+'</b></div><div><small>वर्षा सम्भावना</small><b>'+Math.round(r.r)+'%</b></div><div><small>हावा</small><b>'+Math.round(r.w)+' km/h</b></div></div><button type="button" class="primary my-location-open">पूरा मौसम हेर्नुहोस् →</button>';box.querySelector('.my-location-open').onclick=()=>openDistrict(r);highlightNearest()}
function useMyLocation(){const b=el('useMyLocation'),s=el('myLocationStatus');if(!navigator.geolocation){s.hidden=false;s.innerHTML='<b>📍 Location सुविधा उपलब्ध छैन</b><p>यो ब्राउजरले location support गर्दैन।</p>';return}b?.classList.add('loading');s.hidden=false;s.innerHTML='<b>📍 तपाईंको स्थान खोज्दैछ…</b><p>Browser location permission आवश्यक छ।</p>';navigator.geolocation.getCurrentPosition(pos=>{userLocation={lat:pos.coords.latitude,lon:pos.coords.longitude};nearestDistrict=findNearestDistrict(userLocation.lat,userLocation.lon);b?.classList.remove('loading');renderMyLocation()},()=>{b?.classList.remove('loading');s.innerHTML='<b>📍 स्थान प्राप्त हुन सकेन</b><p>Location permission अनुमति दिनुहोस् वा जिल्ला खोजी प्रयोग गर्नुहोस्।</p>'},{enableHighAccuracy:true,timeout:12000,maximumAge:300000})}
\nfunction selectProvince(next){provinceFilter=next;render();highlightNearest();renderMyLocation()}
function projectPoint(lat,lon,box){const [minX,maxX,minY,maxY]=box;const sx=980/(maxX-minX),sy=720/(maxY-minY);return [((lon-minX)*sx+10).toFixed(1),(730-(lat-minY)*sy).toFixed(1)]}
function renderLocationOverlay(box){const svg=el('districtMap')?.querySelector('.nepal-weather-svg');if(!svg||!userLocation)return;svg.querySelector('.user-location-overlay')?.remove();const [x,y]=projectPoint(userLocation.lat,userLocation.lon,box);const [dx,dy]=nearestDistrict?projectPoint(nearestDistrict.lat,nearestDistrict.lon,box):[x,y];const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('user-location-overlay');g.setAttribute('aria-label','तपाईंको स्थान');g.innerHTML='<line class="location-distance-line" x1="'+x+'" y1="'+y+'" x2="'+dx+'" y2="'+dy+'"></line><circle class="location-pulse" cx="'+x+'" cy="'+y+'" r="12"></circle><circle class="location-marker" cx="'+x+'" cy="'+y+'" r="6"></circle><circle class="nearest-marker" cx="'+dx+'" cy="'+dy+'" r="4"></circle>';svg.appendChild(g)}
\nfunction selectLayer(next){layer=next;document.querySelectorAll('.map-layer').forEach(x=>x.classList.toggle('active',x.dataset.layer===layer));if(layer==='aqi'&&!rows.some(r=>r.a)){loadAqi();return}render()}
function openDistrict(r){const d=el('districtDetail');if(!d)return;const condition=weatherLabel(r.code);d.hidden=false;d.innerHTML='<div class="district-detail-head"><div><small>'+esc(provinceNames[districtProvince[r.e]||'all'])+'</small><h2>'+esc(r.n)+'</h2></div><button type="button" class="district-detail-close" aria-label="बन्द गर्नुहोस्">×</button></div><div class="district-detail-main"><span class="district-detail-icon">'+condition.icon+'</span><div><strong>'+r.t.toFixed(1)+'°C</strong><p>'+esc(condition.text)+'</p></div></div><div class="district-detail-metrics"><div><small>वर्षा सम्भावना</small><b>'+Math.round(r.r)+'%</b></div><div><small>हावा</small><b>'+Math.round(r.w)+' km/h</b></div><div><small>आर्द्रता</small><b>'+Math.round(r.h||0)+'%</b></div><div><small>वर्षा</small><b>'+Number(r.p||0).toFixed(1)+' mm</b></div></div><button type="button" class="primary district-open-full">पूरा मौसम हेर्नुहोस् →</button>';d.querySelector('.district-detail-close').onclick=()=>d.hidden=true;d.querySelector('.district-open-full').onclick=()=>location.href='./?lat='+r.lat+'&lon='+r.lon+'&name='+encodeURIComponent(r.n);d.scrollIntoView({behavior:'smooth',block:'nearest'})}
el('useMyLocation')?.addEventListener('click',useMyLocation);\nel('mapSearch')?.addEventListener('input',e=>{searchTerm=e.target.value.trim();render()});el('mapSearchClear')?.addEventListener('click',()=>{searchTerm='';el('mapSearch').value='';render();el('mapSearch').focus()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const d=el('districtDetail');if(d)d.hidden=true}});document.addEventListener('keydown',e=>{const p=e.target.closest('.district-shape');if(p&&(e.key==='Enter'||e.key===' ')){e.preventDefault();const r=rows.find(x=>x.e===p.dataset.district);if(r)openDistrict(r)}});document.addEventListener('click',e=>{const b=e.target.closest('.map-layer');if(b){selectLayer(b.dataset.layer);return}const p=e.target.closest('.province-filter');if(p){selectProvince(p.value);return}const p=e.target.closest('.district-shape');if(p){const r=rows.find(x=>x.e===p.dataset.district);if(r)openDistrict(r)}})
document.addEventListener('pointermove',e=>{const p=e.target.closest('.district-shape');const tip=el('mapTooltip');if(!tip)return;if(!p){tip.classList.remove('show');return}const r=rows.find(x=>x.e===p.dataset.district);if(!r)return;tip.innerHTML='<b>'+esc(r.n)+'</b><br>'+esc(label(r));tip.style.left=(e.clientX+12)+'px';tip.style.top=(e.clientY+12)+'px';tip.classList.add('show')});
(async()=>{try{el('mapStatus').textContent='नेपालको वास्तविक जिल्ला सीमाना लोड हुँदैछ…';geo=await fetch(GEOJSON_URL).then(r=>r.json());await loadWeather();render()}catch(e){el('mapStatus').textContent='नक्सा लोड हुन सकेन। इन्टरनेट जाँच गर्नुहोस्।'}})();
})();