(()=>{'use strict';
const $=id=>document.getElementById(id),API='https://api.open-meteo.com/v1/forecast';
const peaks={everest:['एभरेस्ट बेस क्याम्प',28.0025,86.8528,5364],annapurna:['अन्नपूर्णा बेस क्याम्प',28.5300,84.0800,4130],langtang:['लाङटाङ',28.2100,85.6100,3430],manaslu:['मनास्लु बेस क्याम्प',28.6500,84.5600,4800],mustang:['मुक्तिनाथ',28.8170,83.8710,3710],dolpo:['डोल्पो',29.0000,82.8000,3600],gosaikunda:['गोसाीकुण्ड',28.0880,85.4140,4380]};
const wx=c=>({0:['सफा','☀️'],1:['मुख्यतः सफा','🌤️'],2:['आंशिक बदली','⛅'],3:['बदली','☁️'],45:['कुहिरो','🌫️'],48:['कुहिरो','🌫️'],51:['हल्का झरी','🌦️'],53:['झरी','🌦️'],55:['झरी','🌧️'],61:['हल्का वर्षा','🌦️'],63:['वर्षा','🌧️'],65:['भारी वर्षा','🌧️'],71:['हल्का हिमपात','🌨️'],73:['हिमपात','❄️'],75:['भारी हिमपात','❄️'],80:['झरी','🌦️'],81:['वर्षा','🌧️'],82:['भारी झरी','🌧️'],95:['चट्याङ','⛈️'],96:['चट्याङ/असिना','⛈️'],99:['चट्याङ/असिना','⛈️']})[c]||['मौसम','🌡️'];
const fmt=v=>Number.isFinite(Number(v))?Math.round(Number(v)*10)/10:'—';
function level(w,r,vis){let s=0;if(w>=50)s+=3;else if(w>=30)s+=2;else if(w>=20)s++;if(r>=60)s+=2;else if(r>=30)s++;if(vis<3000)s+=2;else if(vis<7000)s++;return s>=5?['उच्च सावधानी','bad']:s>=3?['सावधानी','warn']:['अनुकूल','good']}
async function get(p){const q=new URLSearchParams({latitude:p[1],longitude:p[2],timezone:'auto',forecast_days:'1',current:'temperature_2m,weather_code,wind_speed_10m,visibility,snowfall',hourly:'precipitation_probability,snowfall,wind_speed_10m,visibility,weather_code'});const d=await fetch(API+'?'+q).then(r=>{if(!r.ok)throw Error();return r.json()});const c=d.current||{},h=d.hourly||{},i=Math.max(0,(h.time||[]).findIndex(t=>t>=c.time));return {name:p[0],elev:p[3],temp:c.temperature_2m,code:c.weather_code,wind:c.wind_speed_10m,vis:c.visibility,rain:Number(h.precipitation_probability?.[i]??0),snow:Number(c.snowfall??h.snowfall?.[i]??0)}}
function insert(){if($('mountainWeather'))return;const s=document.createElement('section');s.id='mountainWeather';s.className='card mountain-weather';s.innerHTML='<div class="section-head"><div><h2>🏔️ Nepal Mountain Weather</h2><p class="muted">प्रमुख हिमाली तथा ट्रेकिङ गन्तव्यको मौसम र उचाइ हेर्नुहोस्।</p></div><span class="pill">हिमाल मोड</span></div><div class="mountain-grid" id="mountainGrid"><div class="travel-loading">⛰️ हिमाली स्थानको मौसम लोड हुँदैछ…</div></div><p class="national-note">ℹ️ पूर्वानुमान Open-Meteo को स्थान-बिन्दुमा आधारित हो। यो पर्वतारोहण/ट्रेकिङको आधिकारिक सुरक्षा वा मौसम चेतावनी होइन। उच्च उचाइमा स्थानीय गाइड र आधिकारिक चेतावनीलाई प्राथमिकता दिनुहोस्।</p></section>';$('travelWeather')?.insertAdjacentElement('afterend',s);run()}
async function run(){const box=$('mountainGrid');if(!box)return;try{const data=await Promise.all(Object.values(peaks).map(get));box.innerHTML=data.map(x=>{const w=wx(x.code),l=level(x.wind,x.rain,x.vis);return '<article class="mountain-card"><div class="mountain-head"><div><b>'+x.name+'</b><small>📏 '+fmt(x.elev)+' m</small></div><strong>'+w[1]+'</strong></div><div class="mountain-temp">'+fmt(x.temp)+'°C</div><div class="mountain-condition">'+w[0]+'</div><div class="mountain-metrics"><span>☔ '+fmt(x.rain)+'%</span><span>❄️ '+fmt(x.snow)+' cm</span><span>💨 '+fmt(x.wind)+' km/h</span><span>👁️ '+(x.vis>=1000?fmt(x.vis/1000)+' km':fmt(x.vis)+' m')+'</span></div><em class="mountain-'+l[1]+'">'+l[0]+'</em></article>'}).join('')}catch{box.innerHTML='<div class="travel-empty">हिमाली मौसम डाटा ल्याउन सकिएन। फेरि प्रयास गर्नुहोस्।</div>'}}
function boot(){insert()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()})();