(()=>{'use strict';
const $=id=>document.getElementById(id), nf=v=>v==null||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('ne-NP',{maximumFractionDigits:1}).format(Number(v));
const provinces={
'कोशी प्रदेश':['ताप्लेजुङ','पाँचथर','इलाम','झापा','मोरङ','सुनसरी','धनकुटा','तेह्रथुम','संखुवासभा','भोजपुर','सोलुखुम्बु','ओखलढुंगा','खोटाङ','उदयपुर'],
'मधेश प्रदेश':['सप्तरी','सिराहा','धनुषा','महोत्तरी','सर्लाही','रौतहट','बारा','पर्सा'],
'बागमती प्रदेश':['दोलखा','रामेछाप','सिन्धुली','काभ्रेपलाञ्चोक','सिन्धुपाल्चोक','रसुवा','नुवाकोट','धादिङ','काठमाडौं','भक्तपुर','ललितपुर','मकवानपुर','चितवन'],
'गण्डकी प्रदेश':['गोरखा','मनाङ','मुस्ताङ','म्याग्दी','कास्की','लमजुङ','तनहुँ','नवलपुर','स्याङ्जा','पर्वत','बागलुङ'],
'लुम्बिनी प्रदेश':['रुकुम पूर्व','रोल्पा','प्यूठान','गुल्मी','अर्घाखाँची','पाल्पा','नवलपरासी पश्चिम','रुपन्देही','कपिलवस्तु','दाङ','बाँके','बर्दिया'],
'कर्णाली प्रदेश':['डोल्पा','मुगु','हुम्ला','जुम्ला','कालिकोट','दैलेख','जाजरकोट','रुकुम पश्चिम','सल्यान','सुर्खेत'],
'सुदूरपश्चिम प्रदेश':['बझाङ','बाजुरा','अछाम','डोटी','डडेलधुरा','बैतडी','दार्चुला','कञ्चनपुर','कैलाली']};
function pick(name){const i=$('search');if(!i)return;i.value=name;i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));window.scrollTo({top:0,behavior:'smooth'})}
function insert(){if($('nepalPulse'))return;const s=document.createElement('section');s.id='nepalPulse';s.className='card nepal-center';s.innerHTML='<div class="section-head"><div><h2>🇳🇵 Nepal Weather Intelligence Center</h2><p class="muted">नेपालभरको मौसमलाई एउटै ड्यासबोर्डमा बुझ्नुहोस्।</p></div><span id="nepalSeason" class="pill">—</span></div><div class="nepal-kpis" id="nepalKpis"></div><div class="province-head"><h3>७ प्रदेशको मौसम पल्स</h3><span class="muted">स्क्यान गरिएको डाटाबाट</span></div><div class="province-grid" id="provinceGrid"></div><div class="nepal-actions"><button data-place="काठमाडौं">🏙️ काठमाडौं</button><button data-place="मकवानपुर">🏔️ मकवानपुर</button><button data-place="पोखरा">🌄 पोखरा</button><button data-place="मुस्ताङ">🏔️ मुस्ताङ</button><button data-place="लुम्बिनी">🛕 लुम्बिनी</button><button data-place="विराटनगर">🌆 विराटनगर</button></div><p class="national-note">ℹ️ डाटा Open-Meteo र जिल्ला केन्द्र आसपासका बिन्दुमा आधारित हो। यो सरकारी मौसम चेतावनी वा आधिकारिक विपद् सूचना होइन।</p></section>';$('districtExplorer')?.insertAdjacentElement('afterend',s)}
function render(){insert();let saved;try{saved=JSON.parse(localStorage.getItem('mausam_intel')||'null')}catch{}const d=(saved?.data||[]).filter(Boolean);const k=$('nepalKpis');if(!k)return;const temps=d.map(x=>Number(x.temp)).filter(Number.isFinite),avg=temps.length?temps.reduce((a,b)=>a+b,0)/temps.length:null;const hot=[...d].sort((a,b)=>(b.temp??-999)-(a.temp??-999))[0],cold=[...d].sort((a,b)=>(a.temp??999)-(b.temp??999))[0],rain=d.filter(x=>Number(x.rain)>=60).length,uv=d.filter(x=>Number(x.uv)>=7).length;
k.innerHTML=[['🌡️','औसत तापक्रम',avg==null?'—':nf(avg)+'°C','नेपाल स्क्यान'],['🔥','तातो जिल्ला',hot?nf(hot.temp)+'°C':'—',hot?.name||'—'],['🧊','चिसो जिल्ला',cold?nf(cold.temp)+'°C':'—',cold?.name||'—'],['☔','वर्षा जोखिम',nf(rain)+' जिल्ला','सम्भावना ≥ ६०%'],['☀️','उच्च UV',nf(uv)+' जिल्ला','UV ≥ ७']].map((x,i)=>'<button class="nepal-kpi '+(i<3?'clickable':'')+'" '+(i===1&&hot?'data-place="'+hot.name+'"':i===2&&cold?'data-place="'+cold.name+'"':'')+'><span>'+x[0]+'</span><div><small>'+x[1]+'</small><strong>'+x[2]+'</strong><p>'+x[3]+'</p></div></button>').join('');
k.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>pick(b.dataset.place));
const pg=$('provinceGrid');pg.innerHTML=Object.entries(provinces).map(([p,names])=>{const a=d.filter(x=>names.includes(x.name)&&Number.isFinite(Number(x.temp)));const t=a.length?a.reduce((s,x)=>s+Number(x.temp),0)/a.length:null;const r=d.filter(x=>names.includes(x.name)&&Number(x.rain)>=60).length;const place=a[0]?.name||names[0];return '<button class="province-card" data-place="'+place+'"><b>'+p+'</b><strong>'+(t==null?'—':nf(t)+'°C')+'</strong><small>'+nf(a.length)+'/'+nf(names.length)+' जिल्ला · वर्षा जोखिम '+nf(r)+'</small></button>'}).join('');
pg.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>pick(b.dataset.place));document.querySelectorAll('.nepal-actions [data-place]').forEach(b=>b.onclick=()=>pick(b.dataset.place));const month=new Date().getMonth()+1;$('nepalSeason').textContent=month>=6&&month<=9?'🌧️ मनसुन मोड':month>=10||month<=2?'❄️ चिसो मौसम':'🌤️ सामान्य मौसम'}
function boot(){insert();render();window.addEventListener('storage',e=>{if(e.key==='mausam_intel')render()});setInterval(render,10000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();