(()=>{'use strict';
const $=id=>document.getElementById(id);
const API='https://api.open-meteo.com/v1/forecast';
const routes={
 kathmandu-hetauda:{name:'काठमाडौं → हेटौंडा',points:[['काठमाडौं',27.7172,85.3240],['दक्षिणकाली',27.5920,85.2550],['भीमफेदी',27.5500,85.1300],['हेटौंडा',27.4280,85.0320]]},
 kathmandu-pokhara:{name:'काठमाडौं → पोखरा',points:[['काठमाडौं',27.7172,85.3240],['मुग्लिन',27.8667,84.5833],['आँबुखैरेनी',27.9750,84.6300],['पोखरा',28.2096,83.9856]]},
 kathmandu-chitwan:{name:'काठमाडौं → चितवन',points:[['काठमाडौं',27.7172,85.3240],['मुग्लिन',27.8667,84.5833],['भरतपुर',27.6766,84.4359]]},
 kathmandu-lumbini:{name:'काठमाडौं → लुम्बिनी',points:[['काठमाडौं',27.7172,85.3240],['मुग्लिन',27.8667,84.5833],['भरतपुर',27.6766,84.4359],['बुटवल',27.7000,83.4500],['लुम्बिनी',27.4833,83.2760]]}
};
const wx=c=>({0:['सफा','☀️'],1:['मुख्यतः सफा','🌤️'],2:['आंशिक बदली','⛅'],3:['बदली','☁️'],45:['कुहिरो','🌫️'],48:['कुहिरो','🌫️'],51:['हल्का झरी','🌦️'],53:['झरी','🌦️'],55:['झरी','🌧️'],61:['हल्का वर्षा','🌦️'],63:['वर्षा','🌧️'],65:['भारी वर्षा','🌧️'],71:['हल्का हिमपात','🌨️'],73:['हिमपात','❄️'],75:['भारी हिमपात','❄️'],80:['झरी','🌦️'],81:['वर्षा','🌧️'],82:['भारी झरी','🌧️'],95:['चट्याङ','⛈️'],96:['चट्याङ/असिना','⛈️'],99:['चट्याङ/असिना','⛈️']})[c]||['मौसम','🌡️'];
const fmt=v=>Number.isFinite(Number(v))?Math.round(Number(v)*10)/10:'—';
function score(r,w,v){let s=100;s-=Math.min(45,(r||0)*.45);s-=Math.min(25,Math.max(0,(w||0)-20)*1.1);if(v!=null&&v<5000)s-=Math.min(25,(5000-v)/200);return Math.max(0,Math.min(100,Math.round(s)))}
function label(s){return s>=80?['राम्रो','good']:s>=55?['सावधानी','warn']:['खराब','bad']}
async function get(p){const q=new URLSearchParams({latitude:p[1],longitude:p[2],timezone:'auto',forecast_days:'1',current:'temperature_2m,weather_code,wind_speed_10m,visibility',hourly:'precipitation_probability,weather_code,wind_speed_10m,visibility'});const d=await fetch(API+'?'+q).then(r=>{if(!r.ok)throw Error('API error');return r.json()});const c=d.current||{},h=d.hourly||{},i=Math.max(0,(h.time||[]).findIndex(t=>t>=c.time));const rain=Number(h.precipitation_probability?.[i]??0);const vis=Number(c.visibility??h.visibility?.[i]??0);return {name:p[0],temp:c.temperature_2m,code:c.weather_code,wind:c.wind_speed_10m,vis,rain,score:score(rain,c.wind_speed_10m,vis)}}
function insert(){if($('travelWeather'))return;const s=document.createElement('section');s.id='travelWeather';s.className='card travel-weather';s.innerHTML='<div class="section-head"><div><h2>🇳🇵 Nepal Travel Weather</h2><p class="muted">मुख्य यात्रामार्गका checkpoint मा मौसम अवस्था हेर्नुहोस्।</p></div><span class="pill">यात्रा मोड</span></div><div class="travel-controls"><select id="travelRoute" aria-label="यात्रामार्ग">'+Object.entries(routes).map(([k,r])=>'<option value="'+k+'">'+r.name+'</option>').join('')+'</select><button id="travelCheck" class="primary">मौसम जाँच्नुहोस्</button></div><div id="travelSummary" class="travel-summary" hidden></div><div id="travelPoints" class="travel-points"><div class="travel-empty">मार्ग छानेर मौसम जाँच्नुहोस्।</div></div><p class="national-note">ℹ️ यो एपले मौसमका आधारमा बनाएको यात्रा-संकेत मात्र हो। सडक बन्द, पहिरो, ट्राफिक वा सरकारी सुरक्षा चेतावनीको आधिकारिक स्थिति होइन।</p></section>';$('nepalPulse')?.insertAdjacentElement('afterend',s);$('travelCheck').onclick=run}
async function run(){const key=$('travelRoute')?.value||'kathmandu-hetauda',route=routes[key],btn=$('travelCheck'),box=$('travelPoints'),sum=$('travelSummary');btn.disabled=true;btn.textContent='जाँच हुँदैछ…';box.innerHTML='<div class="travel-loading">⏳ '+route.name+' का checkpoint जाँच हुँदैछ…</div>';try{const data=await Promise.all(route.points.map(get));const avg=Math.round(data.reduce((a,x)=>a+x.score,0)/data.length),worst=[...data].sort((a,b)=>a.score-b.score)[0],tag=label(avg);sum.hidden=false;sum.innerHTML='<span>समग्र संकेत</span><strong class="travel-'+tag[1]+'">'+tag[0]+' · '+avg+'/100</strong><small>सबैभन्दा कमजोर checkpoint: '+worst.name+'</small>';box.innerHTML=data.map((x,i)=>{const w=wx(x.code),t=label(x.score);return '<article class="travel-point"><div class="travel-line"><span class="travel-number">'+(i+1)+'</span><span class="travel-dot"></span></div><div class="travel-body"><div class="travel-title"><div><b>'+x.name+'</b><small>'+w[1]+' '+w[0]+'</small></div><strong class="travel-'+t[1]+'">'+x.score+'/100</strong></div><div class="travel-metrics"><span>🌡️ '+fmt(x.temp)+'°C</span><span>☔ '+fmt(x.rain)+'%</span><span>💨 '+fmt(x.wind)+' km/h</span><span>👁️ '+(x.vis>=1000?fmt(x.vis/1000)+' km':fmt(x.vis)+' m')+'</span></div><em>'+t[0]+'</em></div></article>'}).join('')}catch(e){sum.hidden=true;box.innerHTML='<div class="travel-empty">मौसम डाटा ल्याउन सकिएन। इन्टरनेट जडान जाँचेर फेरि प्रयास गर्नुहोस्।</div>'}finally{btn.disabled=false;btn.textContent='मौसम जाँच्नुहोस्'}}
function boot(){insert()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()})();